/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.id.ez.ezpay.view.base;

import co.id.ez.ezpay.app.App;
import co.id.ez.ezpay.app.Common;
import co.id.ez.ezpay.controller.AppController;
import co.id.ez.ezpay.enums.Headers;
import co.id.ez.ezpay.enums.util.Icons;
import co.id.ez.system.core.config.ConfigService;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.ImageIcon;

/**
 *
 * @author RCS
 */
public class APIAccess extends javax.swing.JFrame {

    private final AppController controller = new AppController();
    private String c_uri, g_uri;

    /**
     * Creates new form APIAccess
     */
    public APIAccess() {
        initComponents();
        intForm();
    }

    private void intForm() {
        this.setTitle(System.getProperty("app-name") +" "+ System.getProperty("app-version"));
        ImageIcon img = Icons.ASSETS_ICONS.get();
        this.setIconImage(img.getImage());
        setLocationRelativeTo(null);
        lbl_logo.setIcon(Icons.ASSETS_UNIVERS.get());
        lbl_logo.setText(System.getProperty("app-name"));
        btn_batal.setIcon(Icons.LARGE_CANCEL.get());
        btn_simpan.setIcon(Icons.LARGE_SAVE.get());
        btn_registrasi.setIcon(Icons.LARGE_REGITRASI.get());
    }

    private void close() {
        int opt = Common.showConfirmMessage("Anda ingin keluar dari aplikasi?", this);
        if (opt == 0) {
            System.exit(0);
        }
    }

    private void loadAccess() {

        if (App.environment().isKnownAplication()) {
            g_uri = App.environment().getGatewayUrl();
            c_uri = App.environment().getCentralUrl();

            HashMap<Headers, String> env = App.environment().get();
            txt_client_id.setText(env.get(Headers.DOWN_MAC));
            txt_secretkey.setText(env.get(Headers.ACC_POCKY));
            txt_username.setText(App.environment().getEnu_key());
            txt_password.setText(App.environment().getEnp_val());
        } else {
            String env = ConfigService.getInstance().getString("service.environment", "dev");
            App.environment()
                    .setGuri_base(
                            ConfigService
                                    .getInstance()
                                    .getString("app-config." + env + ".g_uri")
                    );
            App.environment().setCuri_base(ConfigService
                    .getInstance()
                    .getString("app-config." + env + ".c_uri"));

            g_uri = App.environment().getGatewayUrl();
            c_uri = App.environment().getCentralUrl();

            Common.clearText(txt_client_id, txt_secretkey, txt_username, txt_password);
        }

        txt_client_id.requestFocus();
    }

    private void saveAccess() {
        try {
            controller
                    .saveAppEnvironment(
                            g_uri,
                            c_uri,
                            txt_client_id.getText(),
                            txt_secretkey.getText(),
                            txt_username.getText(),
                            txt_password.getText()
                    );
            Common.showInfoMessage("Data berhasil disimpan", this);
            this.dispose();
            new SplashScreen().setVisible(true);
        } catch (SQLException e) {
            Common.errorLog("[SQLException] Failed save environment", e);
            Common.showErrorMessage("Error System, Gagal menyimpan data akses", this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customPanel1 = new co.id.ez.ezpay.util.swings.CustomPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        defaultPanel1 = new co.id.ez.ezpay.util.swings.DefaultPanel();
        btn_batal = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_client_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_secretkey = new javax.swing.JPasswordField();
        txt_password = new javax.swing.JPasswordField();
        btn_registrasi = new javax.swing.JButton();
        lbl_version = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        customPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("API Akses");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_END);

        lbl_logo.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 20)); // NOI18N
        lbl_logo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo.setText("EZ Payment");
        lbl_logo.setPreferredSize(new java.awt.Dimension(100, 28));
        jPanel1.add(lbl_logo, java.awt.BorderLayout.CENTER);

        customPanel1.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setOpaque(false);

        btn_batal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_batal.setText("Keluar");
        btn_batal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_batal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_batal.setPreferredSize(new java.awt.Dimension(100, 25));
        btn_batal.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_batal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        btn_simpan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_simpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_simpan.setPreferredSize(new java.awt.Dimension(100, 25));
        btn_simpan.setVerifyInputWhenFocusTarget(false);
        btn_simpan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_simpan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Client ID");

        txt_client_id.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Secret Key");

        txt_username.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("User Name");

        txt_secretkey.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_secretkey.setPreferredSize(new java.awt.Dimension(64, 25));

        txt_password.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        btn_registrasi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_registrasi.setText("Registrasi");
        btn_registrasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrasi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_registrasi.setPreferredSize(new java.awt.Dimension(100, 25));
        btn_registrasi.setVerifyInputWhenFocusTarget(false);
        btn_registrasi.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_registrasi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_registrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout defaultPanel1Layout = new javax.swing.GroupLayout(defaultPanel1);
        defaultPanel1.setLayout(defaultPanel1Layout);
        defaultPanel1Layout.setHorizontalGroup(
            defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, defaultPanel1Layout.createSequentialGroup()
                        .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_username, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txt_client_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_secretkey, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, defaultPanel1Layout.createSequentialGroup()
                        .addComponent(btn_registrasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        defaultPanel1Layout.setVerticalGroup(
            defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_client_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_secretkey, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_username)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_registrasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lbl_version.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_version.setForeground(new java.awt.Color(255, 255, 255));
        lbl_version.setText("Version 1.0.0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(defaultPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_version)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(defaultPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(lbl_version, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        customPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(customPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        int opy = Common.showConfirmMessage("Simpan data akses ?", this);
        if (opy == 0) {
            saveAccess();
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_registrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrasiActionPerformed
        // TODO add your handling code here:
        int opy = Common.showConfirmMessage("Anda akan melakukan registrasi mitra?", this);
        if (opy == 0) {
            new Registrasi().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_registrasiActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        loadAccess();
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_registrasi;
    private javax.swing.JButton btn_simpan;
    private co.id.ez.ezpay.util.swings.CustomPanel customPanel1;
    private co.id.ez.ezpay.util.swings.DefaultPanel defaultPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_version;
    private javax.swing.JTextField txt_client_id;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JPasswordField txt_secretkey;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
