/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.id.ez.ezpay.view.base;

import co.id.ez.ezpay.MainApps;
import co.id.ez.ezpay.app.App;
import co.id.ez.ezpay.app.Common;
import co.id.ez.ezpay.app.ConnectionManager;
import co.id.ez.ezpay.controller.AppController;
import co.id.ez.ezpay.enums.util.Icons;
import co.id.ez.ezpay.enums.util.InputType;
import co.id.ez.ezpay.msg.BillerResponse;
import co.id.ez.ezpay.msg.registration.RegistrationRequest;
import co.id.ez.ezpay.view.deposit.BalanceView;
import com.json.JSONArray;
import com.json.JSONObject;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author RCS
 */
public class Registrasi extends javax.swing.JFrame {

    private final AppController controller = new AppController();
    private LinkedHashMap<String, JSONArray> data_region;

    /**
     * Creates new form APIAccess
     */
    public Registrasi() {
        initComponents();
        intForm();
    }

    private void intForm() {
        this.setTitle(System.getProperty("app-name") +" "+ System.getProperty("app-version"));
        ImageIcon img = Icons.ASSETS_ICONS.get();
        this.setIconImage(img.getImage());
        setLocationRelativeTo(null);
        lbl_logo.setIcon(Icons.ASSETS_UNIVERS.get());
        lbl_logo.setText(System.getProperty("app-name"));
        lbl_version.setText(System.getProperty("app-version"));
        btn_batal.setIcon(Icons.LARGE_CANCEL.get());
        btn_registrasi.setIcon(Icons.LARGE_REGITRASI.get());
        Common.clearTexts(txt_alamat, txt_clientid, txt_contact_person,
                txt_email, txt_nama_usaha, txt_no_telp, txt_password,
                txt_secretkey, txt_username, txt_no_handphone
        );
        Common.setVisibility(false, panel_access);
        loadDataRegion();
    }

    private void close() {
        int opt = Common.showConfirmMessage("Anda ingin keluar dari aplikasi?", this);
        if (opt == 0) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customPanel1 = new co.id.ez.ezpay.util.swings.CustomPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        defaultPanel1 = new co.id.ez.ezpay.util.swings.DefaultPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_nama_usaha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_contact_person = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        cmb_provinsi = new javax.swing.JComboBox<>();
        cmb_kota = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_no_handphone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        panel_access = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_clientid = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_secretkey = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_batal = new javax.swing.JButton();
        btn_registrasi = new javax.swing.JButton();
        txt_no_telp = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        lbl_version = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        customPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrasi Mitra");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_END);

        lbl_logo.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 20)); // NOI18N
        lbl_logo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo.setText("EZ Payment");
        lbl_logo.setPreferredSize(new java.awt.Dimension(100, 28));
        jPanel1.add(lbl_logo, java.awt.BorderLayout.CENTER);

        customPanel1.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Usaha");

        txt_nama_usaha.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alamat");

        txt_alamat.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Provinsi");

        txt_contact_person.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kota");

        txt_username.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("User Name");

        txt_password.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        cmb_provinsi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmb_provinsi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_provinsi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_provinsiItemStateChanged(evt);
            }
        });

        cmb_kota.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmb_kota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Kontak Person");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("No Telp");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("No Handphone");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Email");

        txt_no_handphone.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("* User name dan password yang akan anda digunakan");

        panel_access.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Akses Mitra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panel_access.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ID Mitra");
        jLabel5.setToolTipText("");

        txt_clientid.setEditable(false);
        txt_clientid.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_clientid.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Secret Key");

        txt_secretkey.setEditable(false);
        txt_secretkey.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_secretkey.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel15.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("* Akses ini bersifat rahasia dan sepenuhnya tanggung jawab mitra");

        jLabel16.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("  Mohon simpan dan jaga kerahasiaan data akses ini untuk menjaga keamanan transaksi");

        javax.swing.GroupLayout panel_accessLayout = new javax.swing.GroupLayout(panel_access);
        panel_access.setLayout(panel_accessLayout);
        panel_accessLayout.setHorizontalGroup(
            panel_accessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txt_clientid)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txt_secretkey)
        );
        panel_accessLayout.setVerticalGroup(
            panel_accessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_accessLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_clientid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_secretkey, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16))
        );

        jPanel3.setOpaque(false);

        btn_batal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_batal.setText("Keluar");
        btn_batal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_batal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_batal.setPreferredSize(new java.awt.Dimension(100, 25));
        btn_batal.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_batal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        btn_registrasi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_registrasi.setText("Registrasi");
        btn_registrasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrasi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_registrasi.setPreferredSize(new java.awt.Dimension(100, 25));
        btn_registrasi.setVerifyInputWhenFocusTarget(false);
        btn_registrasi.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_registrasi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_registrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_registrasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_registrasi, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        txt_no_telp.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        txt_email.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        javax.swing.GroupLayout defaultPanel1Layout = new javax.swing.GroupLayout(defaultPanel1);
        defaultPanel1.setLayout(defaultPanel1Layout);
        defaultPanel1Layout.setHorizontalGroup(
            defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_access, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(defaultPanel1Layout.createSequentialGroup()
                        .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_username, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_password)))
                    .addComponent(txt_nama_usaha)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_alamat)
                    .addGroup(defaultPanel1Layout.createSequentialGroup()
                        .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_no_handphone)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                        .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(defaultPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, defaultPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_email))))
                    .addGroup(defaultPanel1Layout.createSequentialGroup()
                        .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_contact_person)
                            .addComponent(cmb_provinsi, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_kota, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_no_telp))))
                .addContainerGap())
        );
        defaultPanel1Layout.setVerticalGroup(
            defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nama_usaha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_provinsi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_contact_person, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_no_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_no_handphone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(defaultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_username)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_access, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbl_version.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbl_version.setForeground(new java.awt.Color(255, 255, 255));
        lbl_version.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_version.setText("Version 1.0.0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(defaultPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_version, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(defaultPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_version, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        customPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(customPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        if (btn_batal.getText().equalsIgnoreCase("selesai")) {
            int opt = Common.showConfirmMessage("Registrasi selesai, restart aplikasi?", this);
            if (opt == 0) {
                try {
                    MainApps.instance.setLookAndFeel(false);
                    new SplashScreen().setVisible(true);
                } catch (Exception ex) {
                    Common.errorLog("[Exception] Failed start application", ex);
                    Common.showMessage("Fatal Error!\n" + ex.getMessage(), JOptionPane.ERROR_MESSAGE);
                    System.exit(0);
                }
            }
        } else {
            close();
        }
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_registrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrasiActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            int opt = Common.showConfirmMessage("Pastikan data yang anda masukan sudah sesuai.\nLanjukan registrasi mitra?", this);
            if (opt == 0) {
                sendRegistration();
            }
        }
    }//GEN-LAST:event_btn_registrasiActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try {
            if (!ConnectionManager.instance().isAlive()) {
                ConnectionManager.instance().start();
            }
            int loopCekConnection = 0;
            while (!ConnectionManager.instance().isAllConnectionSuccess() && loopCekConnection < 10) {
                loopCekConnection++;
                Thread.sleep(500);
            }
        } catch (InterruptedException e) {
        }

        if (!ConnectionManager.instance().isAllConnectionSuccess()) {
            Common.showWarningMessage("Koneksi ke server gagal, "
                    + "\nmohon periksa jaringan anda!", this);
            System.exit(0);
        }

        txt_nama_usaha.requestFocus();
    }//GEN-LAST:event_formComponentShown

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_formWindowClosing

    private void cmb_provinsiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_provinsiItemStateChanged
        // TODO add your handling code here:
        cmb_kota.removeAllItems();
        cmb_kota.addItem("-- Pilih Kota --");

        List<String> kota = new ArrayList<>();

        if (cmb_provinsi.getSelectedIndex() > 0) {
            JSONArray data = data_region.get(cmb_provinsi.getSelectedItem().toString());
            for (int i = 0; i < data.length(); i++) {
                kota.add(data.getString(i));
            }
        }

        Collections.sort(kota);

        kota.forEach(kotas -> {
            cmb_kota.addItem(kotas);
        });

        cmb_kota.setSelectedIndex(0);
    }//GEN-LAST:event_cmb_provinsiItemStateChanged

    private boolean validateForm() {
        if (txt_nama_usaha.getText().equals("")) {
            Common.showWarningMessage("Mohon isi nama usaha anda!", this);
            txt_nama_usaha.requestFocus();
            return false;
        }

        if (txt_alamat.getText().equals("")) {
            Common.showWarningMessage("Mohon isi alamat usaha anda!", this);
            txt_alamat.requestFocus();
            return false;
        }

        if (txt_contact_person.getText().equals("")) {
            Common.showWarningMessage("Mohon isi kontak person anda!", this);
            txt_contact_person.requestFocus();
            return false;
        }

        if (txt_no_telp.getText().equals("")) {
            Common.showWarningMessage("Mohon isi nomor telpon anda!", this);
            txt_no_telp.requestFocus();
            return false;
        }

        if (txt_no_handphone.getText().equals("")) {
            Common.showWarningMessage("Mohon isi nomor handphone anda!", this);
            txt_no_handphone.requestFocus();
            return false;
        }

        if (txt_email.getText().equals("")) {
            Common.showWarningMessage("Mohon isi email anda!", this);
            txt_email.requestFocus();
            return false;
        }

        if (txt_username.getText().equals("")) {
            Common.showWarningMessage("Mohon isi username yang akan anda gunakan!", this);
            txt_username.requestFocus();
            return false;
        }

        if (txt_password.getText().equals("")) {
            Common.showWarningMessage("Mohon password yang akan anda gunakan!", this);
            txt_password.requestFocus();
            return false;
        }

        if (cmb_provinsi.getSelectedIndex() == 0) {
            Common.showWarningMessage("Mohon pilih provinsi", this);
            cmb_provinsi.requestFocus();
            return false;
        }

        if (cmb_kota.getSelectedIndex() == 0) {
            Common.showWarningMessage("Mohon pilih kota", this);
            cmb_kota.requestFocus();
            return false;
        }
        
        if (!txt_no_telp.getText().equals("") && !txt_no_telp.getText().equals("-")) {
            if (!Common.validateFormatText(txt_no_telp, InputType.PHONE_NUMBER)) {
                Common.showWarningMessage("Format no telpon tidak sesuai!", this);
                txt_no_telp.requestFocus();
                return false;
            }
        }
        
        if (!Common.validateFormatText(txt_no_handphone, InputType.PHONE_NUMBER)) {
            Common.showWarningMessage("Format no handphone tidak sesuai!", this);
            txt_no_handphone.requestFocus();
            return false;
        }
        
        if (!Common.validateFormatText(txt_email, InputType.EMAIL)) {
            Common.showWarningMessage("Format email tidak sesuai!", this);
            txt_no_handphone.requestFocus();
            return false;
        }
        
        if(!Common.validateFormatText(txt_username, InputType.USERNAME)){
            Common.showWarningMessage("Format username tidak sesuai!\n"
                    + "Username minimum 8 digit dengan format huruf atau angka\n"
                    + "dan tidak menggunakan karakter special", this);
            txt_username.requestFocus();
            return false;
        }
        
        if(!Common.validateFormatText(txt_password, InputType.PASSWORD)){
            Common.showWarningMessage("Format password tidak sesuai!\n"
                    + "Password minimum 8 digit dengan kombinasi \n"
                    + "huruf besar, hurud kecil, angka dan special karakter", this);
            txt_password.requestFocus();
            return false;
        }

        return true;
    }

    private void loadDataRegion() {
        data_region = new LinkedHashMap<>();
        JSONArray data_json = Common.getDataRegions();
        cmb_provinsi.removeAllItems();
        cmb_kota.removeAllItems();

        cmb_provinsi.addItem("-- Pilih provinsi --");
        cmb_kota.addItem("-- Pilih Kota --");

        List<String> prov = new ArrayList<>();

        for (int i = 0; i < data_json.length(); i++) {
            JSONObject data = new JSONObject(data_json.get(i).toString());
            String provinsi = data.getString("provinsi");
            JSONArray kota = data.getJSONArray("kota");
            data_region.put(provinsi, kota);
            prov.add(provinsi);
        }

        Collections.sort(prov);

        prov.forEach(string -> {
            cmb_provinsi.addItem(string);
        });

        cmb_provinsi.setSelectedIndex(0);
        cmb_kota.setSelectedIndex(0);
    }

    private void sendRegistration() {
        RegistrationRequest req = new RegistrationRequest();
        req.setAddress(txt_alamat.getText());
        req.setCity(cmb_kota.getSelectedItem().toString());
        req.setContact_person(txt_contact_person.getText());
        req.setCountry("Indonesia");
        req.setEmail(txt_email.getText());
        req.setMitra_name(txt_nama_usaha.getText());
        req.setPassword(txt_password.getText());
        req.setPhone(txt_no_telp.getText());
        req.setProvince(cmb_provinsi.getSelectedItem().toString());
        req.setTagline("-");
        req.setUser_id(txt_username.getText());
        req.setWa_number(txt_no_handphone.getText());

        BillerResponse resp = new BalanceView().sendRequest(req, "POST", true);
        if (resp != null) {
            JSONObject respObj = resp.getPayload();
            if (respObj.getString("rc").equals("2000000")) {
                JSONObject access = new JSONObject(respObj.get("access").toString());
                txt_clientid.setText(access.getString("client_id"));
                txt_secretkey.setText(access.getString("client_key"));
                if (saveAccecc()) {
                    panel_access.setVisible(true);
                    btn_registrasi.setVisible(false);
                    btn_batal.setText("Selesai");
                    btn_batal.setIcon(Icons.LARGE_DONE.get());
                    Common.activateComponent(false, txt_alamat, txt_contact_person, txt_email, txt_nama_usaha,
                            txt_no_handphone, txt_no_telp, txt_password, txt_username, cmb_kota, cmb_provinsi);

                    Common.showInfoMessage("Registrasi berhasil", this);
                }
            }
        }
    }

    private boolean saveAccecc() {
        try {
            controller
                    .saveAppEnvironment(
                            App.environment().getGatewayUrl(),
                            App.environment().getCentralUrl(),
                            txt_clientid.getText(),
                            txt_secretkey.getText(),
                            txt_username.getText(),
                            txt_password.getText()
                    );
            return true;
        } catch (SQLException e) {
            Common.errorLog("[SQLException] Failed save environment", e);
            Common.showErrorMessage("Error System, Gagal menyimpan data akses", this);
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_registrasi;
    private javax.swing.JComboBox<String> cmb_kota;
    private javax.swing.JComboBox<String> cmb_provinsi;
    private co.id.ez.ezpay.util.swings.CustomPanel customPanel1;
    private co.id.ez.ezpay.util.swings.DefaultPanel defaultPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_version;
    private javax.swing.JPanel panel_access;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_clientid;
    private javax.swing.JTextField txt_contact_person;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nama_usaha;
    private javax.swing.JTextField txt_no_handphone;
    private javax.swing.JTextField txt_no_telp;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_secretkey;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
