/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.id.ez.ezpay.view.settings;

import co.id.ez.ezpay.abstracts.AbstractModule;
import co.id.ez.ezpay.app.Common;
import co.id.ez.ezpay.controller.MasterDataContoller;
import co.id.ez.ezpay.enums.MessageType;
import co.id.ez.ezpay.enums.util.Icons;
import co.id.ez.ezpay.util.swings.input.InputTextType;
import com.json.JSONException;
import com.json.JSONObject;
import java.math.BigDecimal;
import java.sql.SQLException;

/**
 *
 * @author RCS
 */
public class SettingHargaJualView extends AbstractModule {

    private final MasterDataContoller controller = new MasterDataContoller();

    /**
     * Creates new form SyncronizeView
     */
    public SettingHargaJualView() {
        initComponents();
        initForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelAdmin = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_value = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmb_pembulatan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txt_min = new javax.swing.JTextField();
        txt_max = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rd_presentase = new javax.swing.JRadioButton();
        rd_rupiah = new javax.swing.JRadioButton();
        btn_simpan = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Harga Jual", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nilai");

        txt_value.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_value.setPreferredSize(new java.awt.Dimension(64, 25));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pembulatan");

        cmb_pembulatan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmb_pembulatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atas", "Bawah", "" }));
        cmb_pembulatan.setMinimumSize(new java.awt.Dimension(72, 25));
        cmb_pembulatan.setPreferredSize(new java.awt.Dimension(72, 25));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Margin Min (Rp)");

        txt_min.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_min.setPreferredSize(new java.awt.Dimension(64, 25));

        txt_max.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_max.setPreferredSize(new java.awt.Dimension(64, 25));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Margin Max (Rp)");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipe");

        buttonGroup1.add(rd_presentase);
        rd_presentase.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rd_presentase.setForeground(new java.awt.Color(255, 255, 255));
        rd_presentase.setText("Presentase");

        buttonGroup1.add(rd_rupiah);
        rd_rupiah.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rd_rupiah.setForeground(new java.awt.Color(255, 255, 255));
        rd_rupiah.setText("Rupiah");

        btn_simpan.setText("SImpan");
        btn_simpan.setPreferredSize(new java.awt.Dimension(72, 25));
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_max, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_min, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_pembulatan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_value, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rd_presentase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rd_rupiah)))
                .addContainerGap(350, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rd_presentase)
                    .addComponent(rd_rupiah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_pembulatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_max, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );

        javax.swing.GroupLayout panelAdminLayout = new javax.swing.GroupLayout(panelAdmin);
        panelAdmin.setLayout(panelAdminLayout);
        panelAdminLayout.setHorizontalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAdminLayout.setVerticalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(panelAdmin, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            int opt = Common.showConfirmMessage("SImpan konfigurasi harga jual?", this);
            if (opt == 0) {
                try {
                    String type = rd_presentase.isSelected() ? "1" : "0";
                    String rountType = cmb_pembulatan.getSelectedIndex() == 0 ? "1" : "0";
                    String value = txt_value.getText().replace(".", "").replace(",", "");
                    String min = txt_min.getText().replace(".", "").replace(",", "");
                    String max = txt_max.getText().replace(".", "").replace(",", "");

                    controller.insertMarginSales(type, value, rountType, min, max);
                    Common.showInfoMessage("Data berhasil disimpan", this);
                    resetForm();
                } catch (JSONException | SQLException e) {
                    Common.errorLog("[JSONException | SQLException] Failed insert data margin", e);
                    Common.showErrorMessage(MessageType.SYSTEM_ERROR, this);
                } catch (Exception e) {
                    Common.errorLog("[Exception] Failed insert data margin", e);
                    Common.showErrorMessage(MessageType.FATAL_ERROR, this);
                }
            }
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    @Override
    public boolean validateForm() {
        if (txt_value.getText().equals("0")) {
            Common.showWarningMessage("Mohon isi nilai dengan benar!", this);
            txt_value.requestFocus();
            return false;
        }

        if (txt_min.getText().equals("0")) {
            Common.showWarningMessage("Mohon isi nilai minimum dengan benar!", this);
            txt_min.requestFocus();
            return false;
        }

        if (txt_max.getText().equals("0")) {
            Common.showWarningMessage("Mohon isi nilai maximum dengan benar!", this);
            txt_max.requestFocus();
            return false;
        }

        BigDecimal val = new BigDecimal(txt_value.getText().replace(".", "").replace(",", ""));
        if (rd_presentase.isSelected()) {
            if (val.compareTo(BigDecimal.valueOf(100)) >= 0) {
                Common.showWarningMessage("Nilai margin tidak boleh lebih dari 100%!", this);
                txt_value.requestFocus();
                return false;
            }
        }

        BigDecimal min = new BigDecimal(txt_min.getText().replace(".", "").replace(",", ""));
        BigDecimal max = new BigDecimal(txt_max.getText().replace(".", "").replace(",", ""));
        
        if (rd_rupiah.isSelected()) {    
            if (min.compareTo(val) > 0) {
                Common.showWarningMessage("Minimum tidak boleh lebih dari nilai!", this);
                txt_min.requestFocus();
                return false;
            }
            
            if (max.compareTo(val) < 0) {
                Common.showWarningMessage("Minimum tidak boleh kurang dari nilai!", this);
                txt_max.requestFocus();
                return false;
            }
        }

        if (max.compareTo(min) < 0) {
            Common.showWarningMessage("Minimum tidak boleh kurang dari nilai minimum!", this);
            txt_max.requestFocus();
            return false;
        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_simpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmb_pembulatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelAdmin;
    private javax.swing.JRadioButton rd_presentase;
    private javax.swing.JRadioButton rd_rupiah;
    private javax.swing.JTextField txt_max;
    private javax.swing.JTextField txt_min;
    private javax.swing.JTextField txt_value;
    // End of variables declaration//GEN-END:variables

    @Override
    public final void initForm() {
        Common.setOpaqueComponent(false, this, jPanel3, panelAdmin, rd_presentase, rd_rupiah);
        btn_simpan.setIcon(Icons.SMALL_SAVE.get());
        InputTextType.makeCurrencyInput(txt_value, txt_min, txt_max);
        resetForm();
    }

    @Override
    public void resetForm() {
        rd_presentase.setSelected(true);
        txt_max.setText("0");
        txt_min.setText("0");
        txt_value.setText("0");
        cmb_pembulatan.setSelectedIndex(0);
        loadData();
    }

    @Override
    public void loadData() {
        try {
            JSONObject data = controller.getMarginSales();
            if (data != null) {
                String type = data.getString("type");
                BigDecimal value = new BigDecimal(data.get("value").toString());
                String round_type = data.getString("round_type");
                BigDecimal margin_min = new BigDecimal(data.get("margin_min").toString());
                BigDecimal margin_max = new BigDecimal(data.get("margin_max").toString());

                if (type.equals("1")) {
                    rd_presentase.setSelected(true);
                } else {
                    rd_rupiah.setSelected(true);
                }

                txt_value.setText(Common.formatRupiah(value.doubleValue(), false));
                txt_max.setText(Common.formatRupiah(margin_max.doubleValue(), false));
                txt_min.setText(Common.formatRupiah(margin_min.doubleValue(), false));

                if (round_type.equals("1")) {
                    cmb_pembulatan.setSelectedIndex(0);
                } else {
                    cmb_pembulatan.setSelectedIndex(1);
                }
            }

            txt_value.requestFocus();
        } catch (JSONException | SQLException e) {
            Common.errorLog("[JSONException | SQLException] Failed load data margin", e);
            Common.showErrorMessage(MessageType.SYSTEM_ERROR, this);
        } catch (Exception e) {
            Common.errorLog("[Exception] Failed load data margin", e);
            Common.showErrorMessage(MessageType.FATAL_ERROR, this);
        }
    }

}
