/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.id.ez.ezpay.view.central;

import co.id.ez.ezpay.enums.util.Icons;
import java.awt.Cursor;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author RCS
 */
public class CentralView extends javax.swing.JPanel {

    private final CentralDataForm[] modulList;

    /**
     * Creates new form CentralView
     *
     * @param pModuleList
     */
    public CentralView(CentralDataForm... pModuleList) {
        this.modulList = pModuleList;
        initComponents();
        initForm();
    }

    private void initForm() {
        setOpaque(false);
        setCursor(new Cursor(Cursor.HAND_CURSOR));
        tabPane.removeAll();
        tabPane.repaint();
        tabPane.revalidate();
        
        new Thread(() -> {
            int index = 0;
            for (CentralDataForm modul : modulList) {
                tabPane.addTab(modul.getDataName(), Icons.SMALL_PAGE.get(), modul);
                tabPane.setDisabledIconAt(index, Icons.SMALL_PAGE_SHITE.get());
                index++;
            }
        }).start();
        
        ChangeListener changeListener = (ChangeEvent changeEvent) -> {
            JTabbedPane sourceTabbedPane = (JTabbedPane) changeEvent.getSource();
            int index = sourceTabbedPane.getSelectedIndex();
            modulList[index].loadData();
        };
        
        tabPane.addChangeListener(changeListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane = new javax.swing.JTabbedPane();

        setLayout(new java.awt.CardLayout());
        add(tabPane, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabPane;
    // End of variables declaration//GEN-END:variables
}
