/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.id.ez.ezpay.view.central;

import co.id.ez.ezpay.model.data.central.CentralVoucherProductModel;
import co.id.ez.ezpay.util.swings.table.TableActionEvent;
import co.id.ez.ezpay.view.master.Master;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Lutfi
 */
public class MasterVoucherView extends CentralDataForm<CentralVoucherProductModel> {

    /**
     * Creates new form MasterVoucherView
     */
    public MasterVoucherView() {
        super(Master.MODULE.getTableHeader(), true, false);
        initComponents();
        initForm();
    }

    @Override
    public final void initForm() {
        setOpaque(false);
        setCursor(new Cursor(Cursor.HAND_CURSOR));
        tabPane.removeAll();
        tabPane.repaint();
        tabPane.revalidate();

        CentralDataForm[] modul = new CentralDataForm[]{
            new MasterVoucherProviderView(), 
            new MasterVoucherProviderPrefixView(),
            new MasterVoucherProductView()
        };
        
        for (CentralDataForm centralDataForm : modul) {
            tabPane.addTab(centralDataForm.getDataName(), centralDataForm);
        }
        
        ChangeListener changeListener = (ChangeEvent changeEvent) -> {
            JTabbedPane sourceTabbedPane = (JTabbedPane) changeEvent.getSource();
            int index = sourceTabbedPane.getSelectedIndex();
            if(index < modul.length){
                modul[index].loadData();
            }
        };

        tabPane.addChangeListener(changeListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane = new javax.swing.JTabbedPane();

        setLayout(new java.awt.CardLayout());
        add(tabPane, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getDataName() {
        return "Master Voucher";
    }

    @Override
    public TableActionEvent getTableActionEvent() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void delete(CentralVoucherProductModel model) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void editData(CentralVoucherProductModel model) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void simpan() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void loadData(String search) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void resetForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void loadData() {

    }
}
