/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.id.ez.ezpay.util.swings.table;

import co.id.ez.ezpay.enums.util.Icons;
import java.awt.Color;
import java.awt.event.ActionEvent;

/**
 *
 * @author RCS
 */
public class ActionPane extends javax.swing.JPanel {

    /**
     * Creates new form Action
     */
    public ActionPane() {
        initComponents();
        btn_action_1.setIcon(Icons.SMALL_DETAIL.get());
        btn_action_2.setIcon(Icons.SMALL_VERIVIED.get());
        btn_action_3.setIcon(Icons.SMALL_SENDTOPRINT.get());
        btn_action_4.setIcon(Icons.SMALL_EDIT.get());
        btn_action_5.setIcon(Icons.SMALL_REMOVE.get());
    }
    
    public void setActiveAction(TableActionEvent event){
        btn_action_1.setVisible(event.canView());
        btn_action_2.setVisible(event.canCheck());
        btn_action_3.setVisible(event.canReprint());
        btn_action_4.setVisible(event.canEdit());
        btn_action_5.setVisible(event.canDelete());
    }
    
    public void initEvent(TableActionEvent event, int row) {
        
        setActiveAction(event);
        
        btn_action_1.addActionListener((ActionEvent ae) -> {
            event.onView(row);
        });
        
        btn_action_2.addActionListener((ActionEvent ae) -> {
            event.onCheckStatus(row);
        });
        
        btn_action_3.addActionListener((ActionEvent ae) -> {
            event.onReprint(row);
        });
        
        btn_action_4.addActionListener((ActionEvent ae) -> {
            event.onEdit(row);
        });
        
        btn_action_5.addActionListener((ActionEvent ae) -> {
            event.onDelete(row);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_action_1 = new co.id.ez.ezpay.util.swings.table.ActionButton();
        btn_action_2 = new co.id.ez.ezpay.util.swings.table.ActionButton();
        btn_action_3 = new co.id.ez.ezpay.util.swings.table.ActionButton();
        btn_action_4 = new co.id.ez.ezpay.util.swings.table.ActionButton();
        btn_action_5 = new co.id.ez.ezpay.util.swings.table.ActionButton();

        setPreferredSize(new java.awt.Dimension(190, 38));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btn_action_1.setPreferredSize(new java.awt.Dimension(28, 28));
        btn_action_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_action_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_action_1MouseExited(evt);
            }
        });
        btn_action_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_action_1ActionPerformed(evt);
            }
        });
        add(btn_action_1);

        btn_action_2.setPreferredSize(new java.awt.Dimension(28, 28));
        add(btn_action_2);

        btn_action_3.setBackground(new java.awt.Color(27, 38, 44));
        btn_action_3.setForeground(new java.awt.Color(27, 38, 44));
        btn_action_3.setPreferredSize(new java.awt.Dimension(28, 28));
        add(btn_action_3);

        btn_action_4.setBackground(new java.awt.Color(27, 38, 44));
        btn_action_4.setForeground(new java.awt.Color(27, 38, 44));
        btn_action_4.setPreferredSize(new java.awt.Dimension(28, 28));
        add(btn_action_4);

        btn_action_5.setBackground(new java.awt.Color(27, 38, 44));
        btn_action_5.setForeground(new java.awt.Color(27, 38, 44));
        btn_action_5.setPreferredSize(new java.awt.Dimension(28, 28));
        add(btn_action_5);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_action_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_action_1MouseEntered
        // TODO add your handling code here:
        btn_action_1.setBackground(Color.red);
    }//GEN-LAST:event_btn_action_1MouseEntered

    private void btn_action_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_action_1MouseExited
        // TODO add your handling code here:
        btn_action_1.setBackground(new Color(199, 199, 199));
    }//GEN-LAST:event_btn_action_1MouseExited

    private void btn_action_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_action_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_action_1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private co.id.ez.ezpay.util.swings.table.ActionButton btn_action_1;
    private co.id.ez.ezpay.util.swings.table.ActionButton btn_action_2;
    private co.id.ez.ezpay.util.swings.table.ActionButton btn_action_3;
    private co.id.ez.ezpay.util.swings.table.ActionButton btn_action_4;
    private co.id.ez.ezpay.util.swings.table.ActionButton btn_action_5;
    // End of variables declaration//GEN-END:variables
}
