-- Script generated by Redgate Compare v1.19.7.21820


-- deployment: Creating dp_vcr_provider_prefix...
CREATE TABLE dp_vcr_provider_prefix (
    id int(11) NOT NULL,
    created_at datetime NULL,
    created_by varchar(50) NULL,
    updated_at datetime NULL,
    updated_by varchar(50) NULL,
    provider_id int(11) NOT NULL,
    prefix char(4) NOT NULL,
    status int(11) NULL DEFAULT 0,
    deleted_at datetime NULL,
    deleted_by varchar(50) NULL
);
ALTER TABLE dp_vcr_provider_prefix 
CHANGE COLUMN id  id INT NOT NULL AUTO_INCREMENT FIRST, 
ADD PRIMARY KEY (id, provider_id, prefix);


-- deployment: Creating dp_vcr_provider...
CREATE TABLE dp_vcr_provider (
    id int(11) NOT NULL,
    created_at datetime NULL,
    created_by varchar(50) NULL,
    updated_at datetime NULL,
    updated_by varchar(50) NULL,
    provider_name varchar(50) NULL,
    status int(11) NULL DEFAULT 0,
    deleted_at datetime NULL,
    deleted_by varchar(50) NULL
);
ALTER TABLE dp_vcr_provider 
CHANGE COLUMN id  id INT NOT NULL AUTO_INCREMENT FIRST, 
ADD PRIMARY KEY (id);


-- deployment: Creating dp_vcr_product...
CREATE TABLE dp_vcr_product (
    id int(11) NOT NULL,
    created_at datetime NULL,
    created_by varchar(50) NULL,
    updated_at datetime NULL,
    updated_by varchar(50) NULL,
    provider_id int(11) NOT NULL,
    voucher_id char(7) NOT NULL,
    voucher_name varchar(50) NULL,
    price bigint(20) NULL DEFAULT 0,
    product_type char(3) NULL,
    status int(11) NULL DEFAULT 0,
    deleted_at datetime NULL,
    deleted_by varchar(50) NULL
);
ALTER TABLE dp_vcr_product 
CHANGE COLUMN id  id INT NOT NULL AUTO_INCREMENT FIRST, 
ADD PRIMARY KEY (id, provider_id, voucher_id);


-- deployment: Creating dp_pre_demon...
CREATE TABLE dp_pre_demon (
    id int(11) NOT NULL,
    created_at datetime NULL,
    created_by varchar(50) NULL,
    updated_at datetime NULL,
    updated_by varchar(50) NULL,
    denom bigint(20) NOT NULL,
    description varchar(50) NULL,
    price_sale bigint(20) NULL DEFAULT 0,
    status int(11) NULL DEFAULT 0,
    deleted_at datetime NULL,
    deleted_by varchar(50) NULL
);
ALTER TABLE dp_pre_demon 
CHANGE COLUMN id  id INT NOT NULL AUTO_INCREMENT FIRST, 
ADD PRIMARY KEY (id, denom);


-- deployment: Creating dp_pam_biller...
CREATE TABLE dp_pam_biller (
    id int(11) NOT NULL,
    created_at datetime NULL,
    created_by varchar(50) NULL,
    updated_at datetime NULL,
    updated_by varchar(50) NULL,
    biller varchar(30) NULL,
    biller_name varchar(40) NULL,
    distric varchar(20) NULL,
    status int(11) NULL DEFAULT 0,
    deleted_at datetime NULL,
    deleted_by varchar(50) NULL
);
ALTER TABLE dp_pam_biller 
CHANGE COLUMN id  id INT NOT NULL AUTO_INCREMENT FIRST, 
ADD PRIMARY KEY (id);


-- deployment: Creating dp_mp_biller...
CREATE TABLE dp_mp_biller (
    id int(11) NOT NULL,
    created_at datetime NULL,
    created_by varchar(50) NULL,
    updated_at datetime NULL,
    updated_by varchar(50) NULL,
    biller varchar(10) NOT NULL,
    biller_name varchar(30) NULL,
    input_1_label varchar(20) NULL,
    input_1_type text NULL,
    input_2_label varchar(20) NULL,
    input_2_type text NULL,
    input_3_label varchar(20) NULL,
    input_3_type text NULL,
    details varchar(255) NULL,
    status int(11) NULL DEFAULT 0,
    deleted_at datetime NULL,
    deleted_by varchar(50) NULL
);
ALTER TABLE dp_mp_biller 
CHANGE COLUMN id  id INT NOT NULL AUTO_INCREMENT FIRST, 
ADD PRIMARY KEY (id, biller);


-- deployment: Creating dp_module_syslist...
CREATE TABLE dp_module_syslist (
    id int(11) NOT NULL,
    created_at datetime NULL,
    created_by varchar(50) NULL,
    updated_at datetime NULL,
    updated_by varchar(50) NULL,
    module_id int(11) NOT NULL,
    path varchar(50) NULL,
    status int(11) NULL DEFAULT 0,
    deleted_at datetime NULL,
    deleted_by varchar(50) NULL
);
ALTER TABLE dp_module_syslist 
CHANGE COLUMN id  id INT NOT NULL AUTO_INCREMENT FIRST, 
ADD PRIMARY KEY (id);


-- deployment: Creating dp_module...
CREATE TABLE dp_module (
    id int(11) NOT NULL,
    created_at datetime NULL,
    created_by varchar(50) NULL,
    updated_at datetime NULL,
    updated_by varchar(50) NULL,
    module_id char(10) NOT NULL,
    module_name varchar(50) NULL,
    status int(11) NULL DEFAULT 0,
    is_need_sign int(11) NULL DEFAULT 1,
    deleted_at datetime NULL,
    deleted_by varchar(50) NULL
);
ALTER TABLE dp_module 
CHANGE COLUMN id  id INT NOT NULL AUTO_INCREMENT FIRST, 
ADD PRIMARY KEY (id, module_id);


-- deployment: Creating ctl_module_mitra...
CREATE TABLE ctl_module_mitra (
    id int(11) NOT NULL,
    created_at datetime NULL,
    created_by varchar(50) NULL,
    updated_at datetime NULL,
    updated_by varchar(50) NULL,
    module_id int(11) NOT NULL,
    mitra_id int(11) NOT NULL,
    adm_fee bigint(20) NULL DEFAULT 0,
    status int(11) NULL DEFAULT 0,
    deleted_at datetime NULL,
    deleted_by varchar(50) NULL
);
ALTER TABLE ctl_module_mitra 
CHANGE COLUMN id  id INT NOT NULL AUTO_INCREMENT FIRST, 
ADD PRIMARY KEY (id, module_id, mitra_id);


-- deployment: Creating ap_version_update_detail...
CREATE TABLE ap_version_update_detail (
    id int(11) NOT NULL,
    created_at datetime NULL,
    created_by varchar(50) NULL,
    updated_at datetime NULL,
    updated_by varchar(50) NULL,
    app_version varchar(15) NOT NULL,
    update_detail varchar(100) NOT NULL,
    update_type char(3) NOT NULL,
    update_file text NOT NULL,
    update_file_type char(3) NOT NULL DEFAULT 'NEW',
    update_file_target text NOT NULL,
    update_seq int(11) NOT NULL
);
ALTER TABLE ap_version_update_detail 
CHANGE COLUMN id  id INT NOT NULL AUTO_INCREMENT FIRST, 
ADD PRIMARY KEY (id, app_version, update_seq);


-- deployment: Creating ap_version_update...
CREATE TABLE ap_version_update (
    id int(11) NOT NULL,
    created_at datetime NULL,
    created_by varchar(50) NULL,
    updated_at datetime NULL,
    updated_by varchar(50) NULL,
    app_version varchar(15) NOT NULL,
    status int(11) NULL DEFAULT 1,
    type char(1) NULL DEFAULT 'A'
);
ALTER TABLE ap_version_update 
CHANGE COLUMN id  id INT NOT NULL AUTO_INCREMENT FIRST, 
ADD PRIMARY KEY (id, app_version);


-- deployment: Creating ap_mitra_detail...
CREATE TABLE ap_mitra_detail (
    id int(11) NOT NULL,
    created_at datetime NULL,
    created_by varchar(50) NULL,
    updated_at datetime NULL,
    updated_by varchar(50) NULL,
    mitra_id int(11) NULL,
    mitra_name varchar(50) NULL,
    phone char(20) NULL,
    wa_number char(20) NULL,
    email varchar(100) NULL,
    address varchar(255) NULL,
    city varchar(50) NULL,
    provincy varchar(50) NULL,
    country varchar(50) NULL,
    contact_person varchar(100) NULL,
    tagline varchar(255) NULL
);
ALTER TABLE ap_mitra_detail 
CHANGE COLUMN id  id INT NOT NULL AUTO_INCREMENT FIRST, 
ADD PRIMARY KEY (id);


-- deployment: Creating ap_mitra_cred_access...
CREATE TABLE ap_mitra_cred_access (
    id int(11) NOT NULL,
    created_at datetime NULL,
    created_by varchar(50) NULL,
    updated_at datetime NULL,
    updated_by varchar(50) NULL,
    cred_id int(11) NOT NULL,
    cred_access varchar(255) NOT NULL,
    deleted_at datetime NULL,
    deleted_by varchar(50) NULL
);
ALTER TABLE ap_mitra_cred_access 
CHANGE COLUMN id  id INT NOT NULL AUTO_INCREMENT FIRST, 
ADD PRIMARY KEY (id, cred_id, cred_access);


-- deployment: Creating ap_mitra_cred...
CREATE TABLE ap_mitra_cred (
    id int(11) NOT NULL,
    created_at datetime NULL,
    created_by varchar(50) NULL,
    updated_at datetime NULL,
    updated_by varchar(50) NULL,
    mitra_id int(11) NOT NULL,
    user_id varchar(255) NOT NULL,
    user_name varchar(50) NULL,
    status int(11) NULL DEFAULT 1,
    deleted_at datetime NULL,
    deleted_by varchar(50) NULL
);
ALTER TABLE ap_mitra_cred 
CHANGE COLUMN id  id INT NOT NULL AUTO_INCREMENT FIRST, 
ADD PRIMARY KEY (id, mitra_id, user_id);


-- deployment: Creating ap_mitra_access...
CREATE TABLE ap_mitra_access (
    id int(11) NOT NULL,
    created_at datetime NULL,
    created_by varchar(50) NULL,
    updated_at datetime NULL,
    updated_by varchar(50) NULL,
    mitra_id int(11) NOT NULL,
    mitra_access varchar(255) NOT NULL,
    device_id int(11) NULL,
    device_name varchar(50) NULL,
    mac_address varchar(50) NULL,
    serial_number char(50) NULL,
    status int(11) NULL DEFAULT 1
);
ALTER TABLE ap_mitra_access 
CHANGE COLUMN id  id INT NOT NULL AUTO_INCREMENT FIRST, 
ADD PRIMARY KEY (id, mitra_id, mitra_access);


-- deployment: Creating ap_mitra...
CREATE TABLE ap_mitra (
    id int(11) NOT NULL,
    created_at datetime NULL,
    created_by varchar(50) NULL,
    updated_at datetime NULL,
    updated_by varchar(50) NULL,
    mitra_id varchar(255) NOT NULL,
    status int(11) NULL DEFAULT 0,
    deleted_at datetime NULL,
    deleted_by varchar(50) NULL
);
ALTER TABLE ap_mitra 
CHANGE COLUMN id  id INT NOT NULL AUTO_INCREMENT FIRST, 
ADD PRIMARY KEY (id, mitra_id);

