-- Script generated by Redgate Compare v1.19.7.21820


-- deployment: Dropping v_vcr_monthly_report...
DROP VIEW v_vcr_monthly_report;


-- deployment: Dropping v_vcr_daily_report...
DROP VIEW v_vcr_daily_report;


-- deployment: Dropping v_pre_monthly_report...
DROP VIEW v_pre_monthly_report;


-- deployment: Dropping v_pre_daily_report...
DROP VIEW v_pre_daily_report;


-- deployment: Dropping v_pos_monthly_report...
DROP VIEW v_pos_monthly_report;


-- deployment: Dropping v_pos_daily_report...
DROP VIEW v_pos_daily_report;


-- deployment: Dropping v_pam_monthly_report...
DROP VIEW v_pam_monthly_report;


-- deployment: Dropping v_pam_daily_report...
DROP VIEW v_pam_daily_report;


-- deployment: Dropping v_mp_monthly_report...
DROP VIEW v_mp_monthly_report;


-- deployment: Dropping v_mp_daily_report...
DROP VIEW v_mp_daily_report;


-- deployment: Dropping v_dashboard_summary_monthly...
DROP VIEW v_dashboard_summary_monthly;


-- deployment: Dropping v_dashboard_summary_daily...
DROP VIEW v_dashboard_summary_daily;


-- deployment: Dropping v_all_summary_monthly...
DROP VIEW v_all_summary_monthly;


-- deployment: Dropping v_vcr_summary_monthly...
DROP VIEW v_vcr_summary_monthly;


-- deployment: Dropping v_pos_summary_monthly...
DROP VIEW v_pos_summary_monthly;


-- deployment: Dropping v_pre_summary_monthly...
DROP VIEW v_pre_summary_monthly;


-- deployment: Dropping v_pam_summary_monthly...
DROP VIEW v_pam_summary_monthly;


-- deployment: Dropping v_mp_summary_monthly...
DROP VIEW v_mp_summary_monthly;


-- deployment: Dropping v_all_summary_daily...
DROP VIEW v_all_summary_daily;


-- deployment: Dropping v_vcr_summary_daily...
DROP VIEW v_vcr_summary_daily;


-- deployment: Dropping v_vcr_transaction...
DROP VIEW v_vcr_transaction;


-- deployment: Dropping v_vcr_product...
DROP VIEW v_vcr_product;


-- deployment: Dropping v_pos_summary_daily...
DROP VIEW v_pos_summary_daily;


-- deployment: Dropping v_pos_transaction...
DROP VIEW v_pos_transaction;


-- deployment: Dropping v_pre_summary_daily...
DROP VIEW v_pre_summary_daily;


-- deployment: Dropping v_pre_transaction...
DROP VIEW v_pre_transaction;


-- deployment: Dropping v_pam_summary_daily...
DROP VIEW v_pam_summary_daily;


-- deployment: Dropping v_pam_transaction...
DROP VIEW v_pam_transaction;


-- deployment: Dropping v_mp_summary_daily...
DROP VIEW v_mp_summary_daily;


-- deployment: Dropping v_mp_transaction...
DROP VIEW v_mp_transaction;


-- deployment: Dropping trx_vcr_sales...
DROP TABLE trx_vcr_sales;


-- deployment: Dropping trx_pre_sales...
DROP TABLE trx_pre_sales;


-- deployment: Dropping trx_pos_sales...
DROP TABLE trx_pos_sales;


-- deployment: Dropping trx_pam_sales...
DROP TABLE trx_pam_sales;


-- deployment: Dropping trx_mp_sales...
DROP TABLE trx_mp_sales;


-- deployment: Dropping mst_employes_position...
DROP TABLE mst_employes_position;


-- deployment: Dropping mst_employes...
DROP TABLE mst_employes;


-- deployment: Dropping dp_vcr_provider_prefix...
DROP TABLE dp_vcr_provider_prefix;


-- deployment: Dropping dp_vcr_provider...
DROP TABLE dp_vcr_provider;


-- deployment: Dropping dp_vcr_product...
DROP TABLE dp_vcr_product;


-- deployment: Dropping dp_pre_demon...
DROP TABLE dp_pre_demon;


-- deployment: Dropping dp_pam_biller...
DROP TABLE dp_pam_biller;


-- deployment: Dropping dp_mp_biller...
DROP TABLE dp_mp_biller;


-- deployment: Dropping ctl_down_acc...
DROP TABLE ctl_down_acc;


-- deployment: Dropping ap_user...
DROP TABLE ap_user;


-- deployment: Dropping ap_margin_sales...
DROP TABLE ap_margin_sales;

