/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.id.ez.ezpay.view.central.mitra;

import co.id.ez.ezpay.app.Common;
import co.id.ez.ezpay.model.data.central.CentralMitraModel;
import co.id.ez.ezpay.msg.data.mitra.UpdateMitra;
import com.json.JSONArray;
import com.json.JSONObject;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;

/**
 *
 * @author RCS
 */
public class MitraDetail extends Mitra {

    private LinkedHashMap<String, JSONArray> data_region;

    /**
     * Creates new form MitraDetail
     */
    public MitraDetail() {
        initComponents();
        initForm();
    }

    private void loadDataRegion() {
        data_region = new LinkedHashMap<>();
        JSONArray data_json = Common.getDataRegions();
        cmb_provinsi.removeAllItems();
        cmb_kota.removeAllItems();

        cmb_provinsi.addItem("-- Pilih provinsi --");
        cmb_kota.addItem("-- Pilih Kota --");

        List<String> prov = new ArrayList<>();

        for (int i = 0; i < data_json.length(); i++) {
            JSONObject data = new JSONObject(data_json.get(i).toString());
            String provinsi = data.getString("provinsi");
            JSONArray kota = data.getJSONArray("kota");
            data_region.put(provinsi, kota);
            prov.add(provinsi);
        }

        Collections.sort(prov);

        prov.forEach(string -> {
            cmb_provinsi.addItem(string);
        });

        cmb_kota.setSelectedIndex(0);
        cmb_provinsi.setSelectedIndex(0);
    }

    private void loadDataKota() {
        cmb_kota.removeAllItems();
        cmb_kota.addItem("-- Pilih Kota --");
        if (cmb_provinsi.getSelectedIndex() > 0) {
            if (data_region.containsKey(cmb_provinsi.getSelectedItem().toString())) {
                JSONArray kota = data_region.get(cmb_provinsi.getSelectedItem().toString());
                for (int i = 0; i < kota.length(); i++) {
                    cmb_kota.addItem(kota.getString(i));
                }
            }
        }
        cmb_kota.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbl_x = new javax.swing.JLabel();
        lbl_x1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_mitra_name = new javax.swing.JTextField();
        cek_aktif = new javax.swing.JCheckBox();
        lbl_x2 = new javax.swing.JLabel();
        lbl_x3 = new javax.swing.JLabel();
        txt_kontak_person = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_mitra_address = new javax.swing.JTextArea();
        cmb_provinsi = new javax.swing.JComboBox<>();
        lbl_x4 = new javax.swing.JLabel();
        lbl_x5 = new javax.swing.JLabel();
        cmb_kota = new javax.swing.JComboBox<>();
        txt_telp = new javax.swing.JTextField();
        lbl_x6 = new javax.swing.JLabel();
        txt_hp = new javax.swing.JTextField();
        lbl_x7 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_x8 = new javax.swing.JLabel();
        txt_tagline = new javax.swing.JTextField();
        lbl_x9 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.CardLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 90));

        lbl_x.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_x.setForeground(new java.awt.Color(255, 255, 255));
        lbl_x.setText("ID");

        lbl_x1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_x1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_x1.setText("Nama Mitra");

        txt_id.setEditable(false);
        txt_id.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_mitra_name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        cek_aktif.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cek_aktif.setForeground(new java.awt.Color(255, 255, 255));
        cek_aktif.setText("Aktif");
        cek_aktif.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cek_aktifItemStateChanged(evt);
            }
        });

        lbl_x2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_x2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_x2.setText("Alamat");

        lbl_x3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_x3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_x3.setText("Provinsi");

        txt_kontak_person.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_mitra_address.setColumns(20);
        txt_mitra_address.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_mitra_address.setLineWrap(true);
        txt_mitra_address.setRows(5);
        txt_mitra_address.setText("jjnjn ajsdjasd jasdjasnd as fasa jdsjd sdkasd janjasdn jasjdnjansd");
        txt_mitra_address.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txt_mitra_address);

        cmb_provinsi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmb_provinsi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_provinsiItemStateChanged(evt);
            }
        });

        lbl_x4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_x4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_x4.setText("Kontak Person");

        lbl_x5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_x5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_x5.setText("Kota");

        cmb_kota.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmb_kota.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_kotaItemStateChanged(evt);
            }
        });

        txt_telp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lbl_x6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_x6.setForeground(new java.awt.Color(255, 255, 255));
        lbl_x6.setText("Telpon");

        txt_hp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lbl_x7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_x7.setForeground(new java.awt.Color(255, 255, 255));
        lbl_x7.setText("No Handphone");

        txt_email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lbl_x8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_x8.setForeground(new java.awt.Color(255, 255, 255));
        lbl_x8.setText("Email");

        txt_tagline.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lbl_x9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_x9.setForeground(new java.awt.Color(255, 255, 255));
        lbl_x9.setText("Tagline");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_x, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cek_aktif, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_x4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_kontak_person, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(lbl_x5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmb_kota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(lbl_x1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_mitra_name, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_x2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_x3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmb_provinsi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_x6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_x7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_hp, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_x8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_x9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tagline, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_x, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cek_aktif, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_x1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mitra_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_x2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_provinsi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_x3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_x5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kontak_person, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_x4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_x6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_hp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_x7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_x8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tagline, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_x9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        add(jPanel2, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void cek_aktifItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cek_aktifItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cek_aktifItemStateChanged

    private void cmb_provinsiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_provinsiItemStateChanged
        // TODO add your handling code here:
        loadDataKota();
    }//GEN-LAST:event_cmb_provinsiItemStateChanged

    private void cmb_kotaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_kotaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_kotaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cek_aktif;
    private javax.swing.JComboBox<String> cmb_kota;
    private javax.swing.JComboBox<String> cmb_provinsi;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_x;
    private javax.swing.JLabel lbl_x1;
    private javax.swing.JLabel lbl_x2;
    private javax.swing.JLabel lbl_x3;
    private javax.swing.JLabel lbl_x4;
    private javax.swing.JLabel lbl_x5;
    private javax.swing.JLabel lbl_x6;
    private javax.swing.JLabel lbl_x7;
    private javax.swing.JLabel lbl_x8;
    private javax.swing.JLabel lbl_x9;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_hp;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_kontak_person;
    private javax.swing.JTextArea txt_mitra_address;
    private javax.swing.JTextField txt_mitra_name;
    private javax.swing.JTextField txt_tagline;
    private javax.swing.JTextField txt_telp;
    // End of variables declaration//GEN-END:variables

    @Override
    public final void initForm() {
        Common.setOpaqueComponent(false, this, jPanel2, cek_aktif);
        resetForm();
    }

    @Override
    public void resetForm() {
        txt_id.setText("Generated by system");
        Common.clearText(txt_email, txt_hp, txt_kontak_person, txt_mitra_name, txt_tagline, txt_telp);
        Common.activateComponent(true, txt_email, txt_hp,
                txt_kontak_person,
                txt_mitra_address, txt_mitra_name,
                txt_tagline, txt_telp,
                cmb_kota, cmb_provinsi);
        txt_mitra_address.setText("");
        txt_mitra_name.requestFocus();
        cek_aktif.setVisible(false);
        cek_aktif.setSelected(false);
        loadDataRegion();
    }

    @Override
    public void initData(CentralMitraModel model) {
        Common.activateComponent(false, txt_email, txt_hp,
                txt_kontak_person,
                txt_mitra_address, txt_mitra_name,
                txt_mitra_address, txt_tagline, txt_telp,
                cmb_kota, cmb_provinsi);
        txt_mitra_address.setEditable(false);
        showData(model);
    }

    @Override
    public void editData(CentralMitraModel model) {
        Common.activateComponent(false, txt_id);
        Common.activateComponent(true, txt_email, txt_hp,
                txt_kontak_person,
                txt_mitra_address, txt_mitra_name,
                txt_mitra_address, txt_tagline, txt_telp,
                cmb_kota, cmb_provinsi);
        txt_mitra_address.setEditable(true);
        showData(model);
    }

    private void showData(CentralMitraModel model) {
        txt_email.setText(model.getEmail());
        txt_hp.setText(model.getHp());
        txt_id.setText(model.getId());
        txt_kontak_person.setText(model.getKontak());
        txt_mitra_address.setText(model.getAlamat());
        txt_mitra_name.setText(model.getNama());
        txt_tagline.setText(model.getTagline());
        txt_telp.setText(model.getTelp());
        cmb_provinsi.setSelectedItem(model.getProvisi());
        cmb_kota.setSelectedItem(model.getKota());
    }
    
    @Override
    public boolean validateForm() {
        
        if(txt_mitra_name.getText().length() == 0){
            Common.showWarningMessage("Mohon isi nama mitra dengan benar", this);
            txt_mitra_name.requestFocus();
            return false;
        }
        
        if(txt_mitra_address.getText().length() == 0){
            Common.showWarningMessage("Mohon isi alamat mitra dengan benar", this);
            txt_mitra_address.requestFocus();
            return false;
        }
        
        if(cmb_provinsi.getSelectedIndex() == 0){
            Common.showWarningMessage("Mohon pilih provinsi", this);
            return false;
        }
        
        if(cmb_kota.getSelectedIndex() == 0){
            Common.showWarningMessage("Mohon pilih kota", this);
            return false;
        }
        
        if(txt_kontak_person.getText().length() == 0){
            Common.showWarningMessage("Mohon isi kontak person mitra dengan benar", this);
            txt_kontak_person.requestFocus();
            return false;
        }
        
        if(txt_telp.getText().length() == 0){
            Common.showWarningMessage("Mohon isi telp mitra dengan benar", this);
            txt_telp.requestFocus();
            return false;
        }
        
        if(txt_hp.getText().length() == 0){
            Common.showWarningMessage("Mohon isi no handphone mitra dengan benar", this);
            txt_telp.requestFocus();
            return false;
        }
        
        if(!Common.validatePhoneNumberFormat(txt_hp.getText())){
            Common.showWarningMessage("Format no handphone tidak sesuai", this);
            txt_hp.requestFocus();
            return false;
        }
        
        if(txt_email.getText().length() == 0){
            Common.showWarningMessage("Mohon isi email mitra dengan benar", this);
            txt_telp.requestFocus();
            return false;
        }
        
        if(!Common.validateEmailFormat(txt_email.getText())){
            Common.showWarningMessage("Format email tidak sesuai", this);
            txt_hp.requestFocus();
            return false;
        }
        
        return true;
    }

    @Override
    public void getData(UpdateMitra request) {
        request.setAddress(txt_mitra_address.getText());
        request.setCity(cmb_kota.getSelectedItem().toString());
        request.setContact_person(txt_kontak_person.getText());
        request.setCountry("Indonesia");
        request.setEmail(txt_email.getText());
        request.setMitra_name(txt_mitra_name.getText());
        request.setPhone(txt_telp.getText());
        request.setWa_number(txt_hp.getText());
        request.setTagline(txt_tagline.getText());
        request.setProvince(cmb_provinsi.getSelectedItem().toString());
    }
}
