/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.id.ez.ezpay.view;

import co.id.ez.ezpay.MainApps;
import co.id.ez.ezpay.app.Common;
import co.id.ez.ezpay.enums.util.Icons;
import co.id.ez.ezpay.enums.MessageType;
import com.jtattoo.plaf.graphite.GraphiteLookAndFeel;
import java.awt.Frame;
import java.util.Properties;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import co.id.ez.ezpay.model.data.detail.DetailDataFactory;
import co.id.ez.ezpay.app.Printer;
import co.id.ez.system.core.log.LogService;

/**
 *
 * @author Lutfi
 */
public class DetailForm extends javax.swing.JDialog {

    private final DetailDataFactory factory;

    /**
     * Creates new form DetailForm
     *
     * @param parent
     * @param modal
     * @param factory
     */
    public DetailForm(Frame parent, boolean modal, DetailDataFactory factory) {
        this(parent, modal, factory, false);
    }

    public DetailForm(Frame parent, boolean modal, DetailDataFactory factory, boolean isPrintable) {
        super(parent, modal);
        initComponents();
        this.factory = factory;
        btn_cetak.setIcon(Icons.LARGE_PRINT.get());
        btn_close.setIcon(Icons.LARGE_CANCEL.get());
        setDataList();
        btn_cetak.setVisible(isPrintable);
    }

    public void setTitle(String title) {
        txt_title.setText(title);
    }

    private void setDataList() {
        new Thread(() -> {
            try {
                DefaultListModel<String> model = new DefaultListModel<>();

                factory.getDetailList().forEach(detailModel -> {
                    model.addElement(detailModel.getValue());
                });

                detaillist.setModel(model);
            } catch (Exception e) {
                LogService
                        .getInstance(this)
                        .dbError()
                        .withCause(e)
                        .log("[Exception] Failed previewDetail", true);
                Common.showErrorMessage(e.getMessage(), this);
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_cetak = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detaillist = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setType(java.awt.Window.Type.POPUP);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        txt_title.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_title.setText("Title");
        txt_title.setPreferredSize(new java.awt.Dimension(32, 25));
        jPanel1.add(txt_title, java.awt.BorderLayout.PAGE_START);

        btn_cetak.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_cetak.setText("Cetak");
        btn_cetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cetak.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cetak.setPreferredSize(new java.awt.Dimension(75, 55));
        btn_cetak.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cetak);

        btn_close.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_close.setText("Tutup");
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_close.setPreferredSize(new java.awt.Dimension(75, 55));
        btn_close.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        jPanel2.add(btn_close);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        detaillist.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        detaillist.setFixedCellHeight(22);
        jScrollPane1.setViewportView(detaillist);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
        MainApps.instance.setLookAndFeel(true);
    }//GEN-LAST:event_formComponentHidden

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
        Printer.instance().print(factory.toString());
        this.setVisible(false);
    }//GEN-LAST:event_btn_cetakActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_close;
    private javax.swing.JList<String> detaillist;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txt_title;
    // End of variables declaration//GEN-END:variables

}
