/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.id.ez.ezpay.view;

import co.id.ez.ezpay.app.Common;
import co.id.ez.ezpay.controller.MasterDataContoller;
import co.id.ez.ezpay.enums.MasterDataType;
import co.id.ez.ezpay.enums.MessageType;
import co.id.ez.ezpay.enums.util.Icons;
import co.id.ez.ezpay.interfaces.DataTable;
import co.id.ez.ezpay.model.data.master.VoucherProductModel;
import co.id.ez.ezpay.util.swings.input.InputTextType;
import co.id.ez.ezpay.view.tabmaster.MasterData;
import java.math.BigDecimal;
import java.sql.SQLException;

/**
 *
 * @author Lutfi
 */
public class PriceInput extends javax.swing.JDialog {
    
    private final MasterDataContoller controller = new MasterDataContoller();
    private final MasterDataType type;
    private final DataTable data;
    private final MasterData frm;

    /**
     * Creates new form PriceInput
     *
     * @param parent
     * @param modal
     * @param type
     * @param data
     * @param masterdata
     */
    public PriceInput(java.awt.Frame parent, boolean modal, MasterDataType type, DataTable data, MasterData masterdata) {
        super(parent, modal);
        initComponents();
        this.type = type;
        this.data = data;
        this.frm = masterdata;
        initForm();
    }
    
    private void initForm() {
        setLocationRelativeTo(null);
        btn_simpan.setIcon(Icons.SMALL_SAVE.get());
        btn_batal.setIcon(Icons.SMALL_CANCEL.get());
        InputTextType.makeCurrencyInput(txt_price);
        initData();
    }
    
    private void initData() {
        switch (type) {
            case VoucherProduct:
                VoucherProductModel model = (VoucherProductModel) data;
                txt_price.setText(Common.formatRupiah(model.getHarga_jual().doubleValue(), false));
                txt_title.setText("Rubah harga: " + model.getVoucherid());
                break;
            default:
                txt_price.setText("-");
                txt_title.setText("-");
                btn_simpan.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_batal = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.BorderLayout(0, 3));

        txt_title.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_title.setText("Rubah harga");
        txt_title.setPreferredSize(new java.awt.Dimension(32, 25));
        jPanel1.add(txt_title, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(382, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Harga");

        txt_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_priceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_price, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_price, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(382, 50));

        btn_batal.setText("Batal");

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_priceActionPerformed
        // TODO add your handling code here:
        btn_simpan.requestFocus();
    }//GEN-LAST:event_txt_priceActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:

        if (validateForm()) {
            try {
                int opt = Common.showConfirmMessage("Simpan perubahan harga?", this);
                if (opt == 0) {
                    switch (type) {
                        case VoucherProduct:
                            VoucherProductModel model = (VoucherProductModel) data;
                            BigDecimal price = new BigDecimal(txt_price.getText().replace(",", "").replace(".", ""));
                            controller.updateVoucherPriceSales(model.getVoucherid(), price);
                            frm.changePrice(txt_price.getText());
                            break;
                        default:
                            break;
                    }
                    this.dispose();
                }
            } catch (SQLException e) {
                Common.errorLog("[SQLException] failed update price sales", e);
                Common.showErrorMessage(MessageType.SYSTEM_ERROR, this);
            }
        }
    }//GEN-LAST:event_btn_simpanActionPerformed
    
    private boolean validateForm() {
        if (txt_price.getText().equals("") || txt_price.getText().equals("0")) {
            Common.showWarningMessage("Mohon isi harga dengan benar!", this);
            return false;
        }
        
        switch (type) {
            case VoucherProduct:
                VoucherProductModel model = (VoucherProductModel) data;
                BigDecimal price = new BigDecimal(txt_price.getText().replace(",", "").replace(".", ""));
                if (price.compareTo(model.getHarga()) <= 0) {
                    Common.showWarningMessage("Harga jual kurang dari harga modal", this);
                    return false;
                } else {
                    return true;
                }
        }
        
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_price;
    private javax.swing.JLabel txt_title;
    // End of variables declaration//GEN-END:variables
}
