-- Script generated by Redgate Compare v1.19.7.21820


-- deployment: Dropping trx_balance_history.ending_balance...
ALTER TABLE trx_balance_history DROP COLUMN ending_balance;


-- deployment: Dropping trx_balance_history.balance...
ALTER TABLE trx_balance_history DROP COLUMN balance;

