-- Script generated by Redgate Compare v1.19.7.21820


-- deployment: Creating trx_balance_history.ending_balance...
ALTER TABLE trx_balance_history ADD COLUMN ending_balance bigint(20) NOT NULL DEFAULT 0;


-- deployment: Creating trx_balance_history.balance...
ALTER TABLE trx_balance_history ADD COLUMN balance bigint(20) NOT NULL DEFAULT 0;

