/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.id.ez.ezpay.view.dashboard;

import co.id.ez.ezpay.app.Common;
import co.id.ez.ezpay.interfaces.DataTable;
import co.id.ez.ezpay.model.data.dashboard.SumariTransaksiModel;
import co.id.ez.ezpay.model.table.DataTableModel;
import co.id.ez.ezpay.util.swings.table.TableHeader;
import com.json.JSONException;
import com.json.JSONObject;
import java.math.BigDecimal;
import java.util.LinkedList;

/**
 *
 * @author RCS
 */
public class DashboardSummaryTransaksi extends javax.swing.JPanel {
    
    private final LinkedList<JSONObject> data;
    private final DataTableModel<DataTable> model;

    /**
     * Creates new form DashboardHistoryTransaksi
     *
     * @param pData
     */
    public DashboardSummaryTransaksi(LinkedList<JSONObject> pData) {
        this.data = pData;
        LinkedList<TableHeader> header = new LinkedList<>();
        header.add(
                TableHeader.create("#", 40)
        );
        
        header.add(
                TableHeader.create("Modul", 120)
        );
        
        header.add(
                TableHeader.create("Tanggal", 40)
        );
        
        header.add(
                TableHeader.create("Jumlah", 40)
        );
        
        header.add(
                TableHeader.create("Total", 100)
        );
        
        model = new DataTableModel(
                header
        );
        initComponents();
        initForm();
    }
    
    public final void initForm() {
        table.fixTable(jScrollPane1);
        Common.clearTexts(txt_total, txt_total_transaksi);
        loadData();
    }
    
    public void loadData() {
        new Thread(() -> {
            try {
                model.clearAllItem(table);
                LinkedList<DataTable> rows = new LinkedList<>();
                int total_trans = 0;
                BigDecimal total = BigDecimal.ZERO;
                if (data != null && data.size() > 0) {
                    int number = 0;
                    for (JSONObject dataHistory : data) {
                        number++;
                        String date = dataHistory.getString("transaction_date");
                        String modul = dataHistory.getString("module");
                        String jml = dataHistory.get("total_transaction").toString();
                        total_trans = total_trans + dataHistory.getInt("total_transaction");
                        BigDecimal amount = new BigDecimal(dataHistory.getDouble("total_amount"));
                        String ttl = Common.formatRupiah(amount.doubleValue());
                        total = total.add(amount);
                        SumariTransaksiModel model = new SumariTransaksiModel("" + number, modul, date, jml, ttl);
                        rows.add(model);
                    }
                }
                model.initDataToTable(table, rows);
                txt_total_transaksi.setText(total_trans + " Transaksi");
                txt_total.setText(Common.formatRupiah(total.doubleValue()));
            } catch (JSONException e) {
                Common.errorLog("[JSONException] Error load data histori", e);
            } catch (Exception e) {
                Common.errorLog("[Exception] Error load data histori", e);
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        content_pane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new co.id.ez.ezpay.util.swings.table.ui.Table();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_total_transaksi = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout(0, 2));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Histori Transaksi");
        jLabel1.setPreferredSize(new java.awt.Dimension(122, 25));
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        jPanel1.add(jSeparator1, java.awt.BorderLayout.PAGE_START);

        content_pane.setOpaque(false);
        content_pane.setLayout(new java.awt.CardLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        content_pane.add(jScrollPane1, "card2");

        jPanel1.add(content_pane, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 70));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Jumlah Transaksi : ");
        jLabel3.setPreferredSize(new java.awt.Dimension(122, 25));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Total Transaksi : ");
        jLabel4.setPreferredSize(new java.awt.Dimension(122, 25));

        txt_total_transaksi.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        txt_total_transaksi.setForeground(new java.awt.Color(51, 51, 51));
        txt_total_transaksi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_total_transaksi.setText("Rp. 1,000,000,000");
        txt_total_transaksi.setPreferredSize(new java.awt.Dimension(122, 25));

        txt_total.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        txt_total.setForeground(new java.awt.Color(51, 51, 51));
        txt_total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_total.setText("Rp. 1,000,000,000");
        txt_total.setPreferredSize(new java.awt.Dimension(122, 25));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_total_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_total_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content_pane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private co.id.ez.ezpay.util.swings.table.ui.Table table;
    private javax.swing.JLabel txt_total;
    private javax.swing.JLabel txt_total_transaksi;
    // End of variables declaration//GEN-END:variables

}
