/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.id.ez.ezpay.view.dashboard;

import co.id.ez.ezpay.app.Common;
import com.json.JSONObject;
import java.awt.Color;
import java.awt.Font;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.LinkedList;
import javax.swing.BorderFactory;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.title.TextTitle;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;

/**
 *
 * @author RCS
 */
public class PieChartTransactionSummary extends javax.swing.JPanel {

    private final LinkedList<JSONObject> data;
    private JFreeChart pieChart;
    private ChartPanel chartPanel;

    /**
     * Creates new form PieChartHistoryTransaksi
     *
     * @param pData
     */
    public PieChartTransactionSummary(LinkedList<JSONObject> pData) {
        this.data = pData;
        initComponents();
        initForm();
    }

    private void initForm() {
        start();
    }

    private PieDataset createDataset() {
        DefaultPieDataset dataset = new DefaultPieDataset();
        HashMap<String, BigDecimal> tHolder = new HashMap<>();

        if (data != null) {
            data.forEach(dataTrans -> {
                String tModule = dataTrans.getString("module");
                BigDecimal tValue = new BigDecimal(dataTrans.getDouble("total_transaction"));
                if (tHolder.containsKey(tModule)) {
                    tHolder.get(tModule).add(tValue);
                } else {
                    tHolder.put(tModule, tValue);
                }
            });
        }

        tHolder.keySet().forEach(module -> {
            dataset.setValue(module, tHolder.get(module).doubleValue());
        });

        return dataset;
    }

    private void loadData() {
        pieChart = ChartFactory.createPieChart(
                "Transaksi Pembayaran dan Topup",
                createDataset(),
                true,
                true,
                false);
        pieChart.setBorderPaint(Color.white);
        pieChart.getPlot().setNoDataMessage("Tidak ada data");
        pieChart.getPlot().setBackgroundPaint(new Color(143,148,251));
        final PiePlot plot = (PiePlot) pieChart.getPlot();
        plot.setLabelGenerator(
                new StandardPieSectionLabelGenerator(
                        " {2}",
                        NumberFormat.getNumberInstance(),
                        NumberFormat.getPercentInstance()
                )
        );
        
        pieChart.setTitle(new TextTitle("Transaksi Pembayaran dan Topup",
                new Font("Arial", java.awt.Font.BOLD, 14)
        )
        );
        chartPanel = new ChartPanel(pieChart);
        chartPanel.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));
        chartPanel.setBackground(Color.white);
        chartPanel.setPreferredSize(new java.awt.Dimension(560, 367));

        removeAll();
        repaint();
        revalidate();
        add(chartPanel);
        repaint();
        revalidate();
    }

    private void start() {
        new Thread(() -> {
            try {
                loadData();
            } catch (Exception e) {
                Common.errorLog("[Exception] Error load data histori", e);
            }

        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(143, 148, 251));
        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
