/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.id.ez.gateway.resource.handler;

import com.json.JSONObject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

/**
 *
 * @author RCS
 */
@Path("/")
public class Hello {

    @Path("/cek_koneksi")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public String cekKoneksi() {
        JSONObject resp = new JSONObject().put("status", "connected");
        return resp.toString();
    }
    
    @GET
    @Produces(MediaType.TEXT_HTML)
    public String hello() {
        return "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
                + "<html dir=\"ltr\" xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" lang=\"id\" style=\"font-family:arial, 'helvetica neue', helvetica, sans-serif\">\n"
                + " <head>\n"
                + "  <meta charset=\"UTF-8\">\n"
                + "  <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\n"
                + "  <meta name=\"x-apple-disable-message-reformatting\">\n"
                + "  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                + "  <meta content=\"telephone=no\" name=\"format-detection\">\n"
                + "  <title>Gateway Payment Service</title><!--[if (mso 16)]>\n"
                + "    <style type=\"text/css\">\n"
                + "    a {text-decoration: none;}\n"
                + "    </style>\n"
                + "    <![endif]--><!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]--><!--[if gte mso 9]>\n"
                + "<xml>\n"
                + "    <o:OfficeDocumentSettings>\n"
                + "    <o:AllowPNG></o:AllowPNG>\n"
                + "    <o:PixelsPerInch>96</o:PixelsPerInch>\n"
                + "    </o:OfficeDocumentSettings>\n"
                + "</xml>\n"
                + "<![endif]--><!--[if !mso]><!-- -->\n"
                + "  <link href=\"https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700;800&display=swap\" rel=\"stylesheet\">\n"
                + "  <link href=\"https://fonts.googleapis.com/css2?family=Righteous&display=swap\" rel=\"stylesheet\"><!--<![endif]-->\n"
                + "  <style type=\"text/css\">\n"
                + "#outlook a {\n"
                + "	padding:0;\n"
                + "}\n"
                + ".es-button {\n"
                + "	mso-style-priority:100!important;\n"
                + "	text-decoration:none!important;\n"
                + "}\n"
                + "a[x-apple-data-detectors] {\n"
                + "	color:inherit!important;\n"
                + "	text-decoration:none!important;\n"
                + "	font-size:inherit!important;\n"
                + "	font-family:inherit!important;\n"
                + "	font-weight:inherit!important;\n"
                + "	line-height:inherit!important;\n"
                + "}\n"
                + ".es-desk-hidden {\n"
                + "	display:none;\n"
                + "	float:left;\n"
                + "	overflow:hidden;\n"
                + "	width:0;\n"
                + "	max-height:0;\n"
                + "	line-height:0;\n"
                + "	mso-hide:all;\n"
                + "}\n"
                + "@media only screen and (max-width:600px) {p, ul li, ol li, a { line-height:150%!important } h1, h2, h3, h1 a, h2 a, h3 a { line-height:120% } h1 { font-size:50px!important; text-align:center!important } h2 { font-size:26px!important; text-align:left } h3 { font-size:20px!important; text-align:left } .es-header-body h1 a, .es-content-body h1 a, .es-footer-body h1 a { font-size:50px!important; text-align:center!important } .es-header-body h2 a, .es-content-body h2 a, .es-footer-body h2 a { font-size:26px!important; text-align:left } .es-header-body h3 a, .es-content-body h3 a, .es-footer-body h3 a { font-size:20px!important; text-align:left } .es-menu td a { font-size:12px!important } .es-header-body p, .es-header-body ul li, .es-header-body ol li, .es-header-body a { font-size:14px!important } .es-content-body p, .es-content-body ul li, .es-content-body ol li, .es-content-body a { font-size:16px!important } .es-footer-body p, .es-footer-body ul li, .es-footer-body ol li, .es-footer-body a { font-size:12px!important } .es-infoblock p, .es-infoblock ul li, .es-infoblock ol li, .es-infoblock a { font-size:12px!important } *[class=\"gmail-fix\"] { display:none!important } .es-m-txt-c, .es-m-txt-c h1, .es-m-txt-c h2, .es-m-txt-c h3 { text-align:center!important } .es-m-txt-r, .es-m-txt-r h1, .es-m-txt-r h2, .es-m-txt-r h3 { text-align:right!important } .es-m-txt-l, .es-m-txt-l h1, .es-m-txt-l h2, .es-m-txt-l h3 { text-align:left!important } .es-m-txt-r img, .es-m-txt-c img, .es-m-txt-l img { display:inline!important } .es-button-border { display:inline-block!important } a.es-button, button.es-button { font-size:20px!important; display:inline-block!important } .es-adaptive table, .es-left, .es-right { width:100%!important } .es-content table, .es-header table, .es-footer table, .es-content, .es-footer, .es-header { width:100%!important; max-width:600px!important } .es-adapt-td { display:block!important; width:100%!important } .adapt-img { width:100%!important; height:auto!important } .es-m-p0 { padding:0!important } .es-m-p0r { padding-right:0!important } .es-m-p0l { padding-left:0!important } .es-m-p0t { padding-top:0!important } .es-m-p0b { padding-bottom:0!important } .es-m-p20b { padding-bottom:20px!important } .es-mobile-hidden, .es-hidden { display:none!important } tr.es-desk-hidden, td.es-desk-hidden, table.es-desk-hidden { width:auto!important; overflow:visible!important; float:none!important; max-height:inherit!important; line-height:inherit!important } tr.es-desk-hidden { display:table-row!important } table.es-desk-hidden { display:table!important } td.es-desk-menu-hidden { display:table-cell!important } .es-menu td { width:1%!important } table.es-table-not-adapt, .esd-block-html table { width:auto!important } table.es-social { display:inline-block!important } table.es-social td { display:inline-block!important } .es-desk-hidden { display:table-row!important; width:auto!important; overflow:visible!important; max-height:inherit!important } .es-m-p5 { padding:5px!important } .es-m-p5t { padding-top:5px!important } .es-m-p5b { padding-bottom:5px!important } .es-m-p5r { padding-right:5px!important } .es-m-p5l { padding-left:5px!important } .es-m-p10 { padding:10px!important } .es-m-p10t { padding-top:10px!important } .es-m-p10b { padding-bottom:10px!important } .es-m-p10r { padding-right:10px!important } .es-m-p10l { padding-left:10px!important } .es-m-p15 { padding:15px!important } .es-m-p15t { padding-top:15px!important } .es-m-p15b { padding-bottom:15px!important } .es-m-p15r { padding-right:15px!important } .es-m-p15l { padding-left:15px!important } .es-m-p20 { padding:20px!important } .es-m-p20t { padding-top:20px!important } .es-m-p20r { padding-right:20px!important } .es-m-p20l { padding-left:20px!important } .es-m-p25 { padding:25px!important } .es-m-p25t { padding-top:25px!important } .es-m-p25b { padding-bottom:25px!important } .es-m-p25r { padding-right:25px!important } .es-m-p25l { padding-left:25px!important } .es-m-p30 { padding:30px!important } .es-m-p30t { padding-top:30px!important } .es-m-p30b { padding-bottom:30px!important } .es-m-p30r { padding-right:30px!important } .es-m-p30l { padding-left:30px!important } .es-m-p35 { padding:35px!important } .es-m-p35t { padding-top:35px!important } .es-m-p35b { padding-bottom:35px!important } .es-m-p35r { padding-right:35px!important } .es-m-p35l { padding-left:35px!important } .es-m-p40 { padding:40px!important } .es-m-p40t { padding-top:40px!important } .es-m-p40b { padding-bottom:40px!important } .es-m-p40r { padding-right:40px!important } .es-m-p40l { padding-left:40px!important } }\n"
                + "@media screen and (max-width:384px) {.mail-message-content { width:414px!important } }\n"
                + "</style>\n"
                + " </head>\n"
                + " <body style=\"width:100%;font-family:arial, 'helvetica neue', helvetica, sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0\">\n"
                + "  <div dir=\"ltr\" class=\"es-wrapper-color\" lang=\"id\" style=\"background-color:#314B70\"><!--[if gte mso 9]>\n"
                + "			<v:background xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"t\">\n"
                + "				<v:fill type=\"tile\" color=\"#314B70\"></v:fill>\n"
                + "			</v:background>\n"
                + "		<![endif]-->\n"
                + "   <table class=\"es-wrapper\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top;background-color:#314B70\">\n"
                + "     <tr>\n"
                + "      <td valign=\"top\" style=\"padding:0;Margin:0\">\n"
                + "       <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-content\" align=\"center\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%\">\n"
                + "         <tr>\n"
                + "          <td align=\"center\" style=\"padding:0;Margin:0\">\n"
                + "           <table bgcolor=\"#ffffff\" class=\"es-content-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" background=\"https://ecwiwpr.stripocdn.email/content/guids/CABINET_dd9759b09de82ede623cff0b42f718ca19c0a4f85f6337f81c705fd693708d47/images/simonleezftw1kvehgunsplash_1_1.png\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#07021F;background-repeat:no-repeat;width:600px;background-image:url(https://ecwiwpr.stripocdn.email/content/guids/CABINET_dd9759b09de82ede623cff0b42f718ca19c0a4f85f6337f81c705fd693708d47/images/simonleezftw1kvehgunsplash_1_1.png);background-position:center bottom\">\n"
                + "             <tr>\n"
                + "              <td class=\"es-m-p40t\" align=\"left\" style=\"Margin:0;padding-top:20px;padding-left:20px;padding-right:20px;padding-bottom:40px\">\n"
                + "               <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                + "                 <tr>\n"
                + "                  <td align=\"center\" valign=\"top\" style=\"padding:0;Margin:0;width:560px\">\n"
                + "                   <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                + "                     <tr class=\"es-mobile-hidden\">\n"
                + "                      <td align=\"center\" height=\"85\" style=\"padding:0;Margin:0\"></td>\n"
                + "                     </tr>\n"
                + "                     <tr>\n"
                + "                      <td align=\"center\" style=\"padding:0;Margin:0;padding-bottom:15px;font-size:0px\"><a target=\"_blank\" href=\"https://viewstripo.email\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#FFFFFF;font-size:18px\"><img src=\"https://ecwiwpr.stripocdn.email/content/guids/CABINET_dd9759b09de82ede623cff0b42f718ca19c0a4f85f6337f81c705fd693708d47/images/bluebubblelikebuttoniconthumbsuplikesignfeedbackconceptwhitebackground3drendering.png\" alt style=\"display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic\" width=\"60\"></a></td>\n"
                + "                     </tr>\n"
                + "                     <tr>\n"
                + "                      <td align=\"center\" style=\"padding:0;Margin:0;padding-bottom:25px;letter-spacing:5px\"><p style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif;line-height:18px;color:#efefef;font-size:12px\">Pengalaman anda sangat berharga</p></td>\n"
                + "                     </tr>\n"
                + "                     <tr>\n"
                + "                      <td align=\"center\" style=\"padding:0;Margin:0;padding-bottom:40px\"><h1 style=\"Margin:0;line-height:72px;mso-line-height-rule:exactly;font-family:Righteous, sans-serif;font-size:60px;font-style:normal;font-weight:bold;color:#FFFFFF\">Selamat Datang</h1><p style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif;line-height:27px;color:#FFFFFF;font-size:18px\">.................................................................</p></td>\n"
                + "                     </tr>\n"
                + "                     <tr>\n"
                + "                      <td align=\"center\" class=\"es-m-p0r es-m-p0l\" style=\"padding:0;Margin:0;padding-bottom:40px;padding-left:40px;padding-right:40px\"><p style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif;line-height:27px;color:#FFFFFF;font-size:18px\">Kami melayani anda dengan sepenuh hati</p></td>\n"
                + "                     </tr>\n"
                + "                     <tr>\n"
                + "                      <td align=\"center\" style=\"padding:0;Margin:0;padding-top:20px;padding-bottom:40px\"><!--[if mso]><a href=\"\" target=\"_blank\" hidden>\n"
                + "	<v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" esdevVmlButton href=\"\" \n"
                + "                style=\"height:58px; v-text-anchor:middle; width:309px\" arcsize=\"50%\" stroke=\"f\"  fillcolor=\"#f87575\">\n"
                + "		<w:anchorlock></w:anchorlock>\n"
                + "		<center style='color:#ffffff; font-family:Righteous, sans-serif; font-size:23px; font-weight:400; line-height:23px;  mso-text-raise:1px'>Hubungi Kami</center>\n"
                + "	</v:roundrect></a>\n"
                + "<![endif]--><!--[if !mso]><!-- --><span class=\"msohide es-button-border\" style=\"border-style:solid;border-color:#2CB543;background:#F87575;border-width:0px;display:inline-block;border-radius:30px;width:auto;mso-hide:all\"><a href=\"\" class=\"es-button es-button-1675432559559\" target=\"_blank\" style=\"mso-style-priority:100 !important;text-decoration:none;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;color:#FFFFFF;font-size:24px;display:inline-block;background:#F87575;border-radius:30px;font-family:Righteous, sans-serif;font-weight:normal;font-style:normal;line-height:29px;width:auto;text-align:center;padding:15px 40px;mso-padding-alt:0;mso-border-alt:10px solid #F87575;letter-spacing:5px\">Hubungi Kami</a></span><!--<![endif]--></td>\n"
                + "                     </tr>\n"
                + "                   </table></td>\n"
                + "                 </tr>\n"
                + "               </table></td>\n"
                + "             </tr>\n"
                + "           </table></td>\n"
                + "         </tr>\n"
                + "       </table>\n"
                + "       <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-footer\" align=\"center\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;background-color:transparent;background-repeat:repeat;background-position:center top\">\n"
                + "         <tr>\n"
                + "          <td align=\"center\" style=\"padding:0;Margin:0\">\n"
                + "           <table bgcolor=\"#ffffff\" class=\"es-footer-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#07021F;width:600px\">\n"
                + "             <tr>\n"
                + "              <td align=\"left\" style=\"Margin:0;padding-left:20px;padding-right:20px;padding-top:40px;padding-bottom:40px\">\n"
                + "               <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                + "                 <tr>\n"
                + "                  <td align=\"left\" style=\"padding:0;Margin:0;width:560px\">\n"
                + "                   <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                + "                     <tr>\n"
                + "                      <td align=\"center\" style=\"padding:0;Margin:0;font-size:0\">\n"
                + "                       <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-table-not-adapt es-social\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                + "                         <tr>\n"
                + "                          <td align=\"center\" valign=\"top\" style=\"padding:0;Margin:0;padding-right:40px\"><a target=\"_blank\" href=\"https://viewstripo.email\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#CCCCCC;font-size:12px\"><img src=\"https://ecwiwpr.stripocdn.email/content/assets/img/social-icons/logo-gray/facebook-logo-gray.png\" alt=\"Fb\" title=\"Facebook\" height=\"24\" style=\"display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic\"></a></td>\n"
                + "                          <td align=\"center\" valign=\"top\" style=\"padding:0;Margin:0;padding-right:40px\"><a target=\"_blank\" href=\"https://viewstripo.email\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#CCCCCC;font-size:12px\"><img src=\"https://ecwiwpr.stripocdn.email/content/assets/img/social-icons/logo-gray/twitter-logo-gray.png\" alt=\"Tw\" title=\"Twitter\" height=\"24\" style=\"display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic\"></a></td>\n"
                + "                          <td align=\"center\" valign=\"top\" style=\"padding:0;Margin:0;padding-right:40px\"><a target=\"_blank\" href=\"https://viewstripo.email\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#CCCCCC;font-size:12px\"><img src=\"https://ecwiwpr.stripocdn.email/content/assets/img/social-icons/logo-gray/instagram-logo-gray.png\" alt=\"Ig\" title=\"Instagram\" height=\"24\" style=\"display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic\"></a></td>\n"
                + "                          <td align=\"center\" valign=\"top\" style=\"padding:0;Margin:0\"><a target=\"_blank\" href=\"https://viewstripo.email\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#CCCCCC;font-size:12px\"><img src=\"https://ecwiwpr.stripocdn.email/content/assets/img/social-icons/logo-gray/youtube-logo-gray.png\" alt=\"Yt\" title=\"Youtube\" height=\"24\" style=\"display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic\"></a></td>\n"
                + "                         </tr>\n"
                + "                       </table></td>\n"
                + "                     </tr>\n"
                + "                     <tr>\n"
                + "                      <td align=\"center\" style=\"padding:20px;Margin:0;font-size:0\">\n"
                + "                       <table border=\"0\" width=\"65%\" height=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                + "                         <tr>\n"
                + "                          <td style=\"padding:0;Margin:0;border-bottom:1px solid #cccccc;background:unset;height:1px;width:100%;margin:0px\"></td>\n"
                + "                         </tr>\n"
                + "                       </table></td>\n"
                + "                     </tr>\n"
                + "                     <tr>\n"
                + "                      <td style=\"padding:0;Margin:0\">\n"
                + "                       <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"es-menu\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\n"
                + "                         <tr class=\"links\">\n"
                + "                          <td align=\"right\" valign=\"top\" style=\"Margin:0;padding-top:10px;padding-bottom:10px;padding-left:15px;padding-right:15px;border:0\"><a target=\"_blank\" href=\"https://viewstripo.email\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:none;display:block;font-family:Manrope, sans-serif;color:#CCCCCC;font-size:12px;font-weight:normal\">Privacy Policy</a></td>\n"
                + "                          <td align=\"left\" valign=\"top\" style=\"Margin:0;padding-top:10px;padding-bottom:10px;padding-left:15px;padding-right:15px;border:0\"><a target=\"_blank\" href=\"https://viewstripo.email\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:none;display:block;font-family:Manrope, sans-serif;color:#CCCCCC;font-size:12px;font-weight:normal\">Terms of use</a></td>\n"
                + "                         </tr>\n"
                + "                       </table></td>\n"
                + "                     </tr>\n"
                + "                     <tr>\n"
                + "                      <td align=\"center\" style=\"padding:0;Margin:0;padding-top:15px;padding-bottom:40px\"><p style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Manrope, sans-serif;line-height:18px;color:#CCCCCC;font-size:12px\">No longer want to receive these emails? <a target=\"_blank\" href=\"\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#CCCCCC;font-size:12px\">Unsubscribe.</a></p></td>\n"
                + "                     </tr>\n"
                + "                   </table></td>\n"
                + "                 </tr>\n"
                + "               </table></td>\n"
                + "             </tr>\n"
                + "           </table></td>\n"
                + "         </tr>\n"
                + "       </table></td>\n"
                + "     </tr>\n"
                + "   </table>\n"
                + "  </div>\n"
                + " </body>\n"
                + "</html>";
    }

}
