/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.id.ez.ezpay.view.module;

import co.id.ez.ezpay.abstracts.AbstractModule;
import co.id.ez.ezpay.app.Common;
import co.id.ez.ezpay.app.SessionManager;
import co.id.ez.ezpay.enums.Modul;
import co.id.ez.ezpay.util.swings.card.Card;
import co.id.ez.ezpay.view.dashboard.LineChartSales;
import co.id.ez.ezpay.view.dashboard.DashboardSummaryLoader;
import co.id.ez.ezpay.view.dashboard.PassTransaction;
import co.id.ez.ezpay.view.dashboard.OngoingTransaction;
import co.id.ez.ezpay.view.dashboard.TransactionSummary;
import java.awt.Dimension;
import javax.swing.JPanel;

/**
 *
 * @author Lutfi
 */
public class Dashboard extends AbstractModule {

    private final DashboardSummaryLoader dashboardSummaryLoader;

    /**
     * Creates new form PLNPrepaidModule
     */
    public Dashboard() {
        dashboardSummaryLoader = new DashboardSummaryLoader(this);
        initComponents();
        initForm();
    }

    @Override
    public final void initForm() {
        Common.setOpaqueComponent(false, this,
                panel_parent, jPanel5, jPanel6, jPanel7, panel_dashboard_summary, jPanel1);
        txt_greating.setText("Hai "+ SessionManager.instance().getName()+", Selamat datang di EZPayment");
        if (SessionManager.instance().isAllowedAccess(Modul.DASHBOARD.getAccess())) {
            resetForm();
            loadData();
            tab_pane.addTab("Transaksi Berjalan",new OngoingTransaction());
            tab_pane.addTab("Transaksi Sebelumnya",new PassTransaction());
        }
    }

    public void addDashboardSummary(Card... cards) {
        for (Card card : cards) {
            panel_dashboard_summary.add(card);
            panel_dashboard_summary.repaint();
            panel_dashboard_summary.revalidate();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_parent = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txt_greating = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        panel_dashboard_summary = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        tab_pane = new javax.swing.JTabbedPane();

        setPreferredSize(new java.awt.Dimension(1055, 302));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        panel_parent.setOpaque(false);

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setOpaque(false);
        jPanel5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel5formComponentShown(evt);
            }
        });
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setPreferredSize(new java.awt.Dimension(294, 30));

        txt_greating.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_greating.setForeground(new java.awt.Color(255, 255, 255));
        txt_greating.setText("Hai Super Admin, Selamat Datang di EZPayment");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_greating, javax.swing.GroupLayout.DEFAULT_SIZE, 1031, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_greating, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel7.setLayout(new java.awt.BorderLayout(0, 3));

        panel_dashboard_summary.setLayout(new java.awt.GridLayout(1, 4, 5, 0));
        jPanel7.add(panel_dashboard_summary, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout(0, 3));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 2));
        jPanel1.add(jSeparator1, java.awt.BorderLayout.PAGE_START);

        tab_pane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(tab_pane, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel7, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panel_parentLayout = new javax.swing.GroupLayout(panel_parent);
        panel_parent.setLayout(panel_parentLayout);
        panel_parentLayout.setHorizontalGroup(
            panel_parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1043, Short.MAX_VALUE)
        );
        panel_parentLayout.setVerticalGroup(
            panel_parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_parentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void jPanel5formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel5formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5formComponentShown

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
        dashboardSummaryLoader.stopWorker();
        dashboardSummaryLoader.stop();
    }//GEN-LAST:event_formComponentHidden


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panel_dashboard_summary;
    private javax.swing.JPanel panel_parent;
    private javax.swing.JTabbedPane tab_pane;
    private javax.swing.JLabel txt_greating;
    // End of variables declaration//GEN-END:variables

    @Override
    public final void resetForm() {
        int width = panel_parent.getWidth();
        int height = panel_parent.getHeight();
        panel_parent.setPreferredSize(new Dimension(width, height + 300));
    }

    @Override
    public void loadData() {
        panel_dashboard_summary.removeAll();
        panel_dashboard_summary.repaint();
        panel_dashboard_summary.revalidate();
        dashboardSummaryLoader.start();
    }
}
