/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.id.ez.ezpay.view.module;

import co.id.ez.database.query.QueryBuilder;
import co.id.ez.database.query.QueryType;
import co.id.ez.ezpay.util.swings.PopupMenu;
import java.awt.event.KeyEvent;
import co.id.ez.ezpay.abstracts.AbstractModule;
import co.id.ez.ezpay.app.App;
import co.id.ez.ezpay.app.Common;
import co.id.ez.ezpay.enums.util.Icons;
import co.id.ez.ezpay.enums.MessageType;
import co.id.ez.ezpay.model.data.DataSearch;
import co.id.ez.ezpay.model.data.detail.Field;
import co.id.ez.ezpay.model.data.search.VoucherModel;
import co.id.ez.ezpay.msg.vcr.VoucherInquiry;
import co.id.ez.ezpay.msg.vcr.VoucherPayment;
import co.id.ez.system.core.rc.RC;
import com.json.JSONException;
import com.json.JSONObject;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.LinkedList;

/**
 *
 * @author Lutfi
 */
public class VoucherModule extends AbstractModule {

    private DataSearch<VoucherModel> dataHolderList;
    private VoucherModel product;

    /**
     * Creates new form VoucherModule
     */
    public VoucherModule() {
        initComponents();
        initForm();
        initListener();
    }

    @Override
    public final void initForm() {
        Common.setOpaqueComponent(false, jPanel1, jPanel2, rd_ewallet, rd_paketdata, rd_voucher, rd_emoney, jPanel3, jPanel4);
        btn_cek.setIcon(Icons.LARGE_DONE.get());
        btn_batal.setIcon(Icons.LARGE_CANCEL.get());
        btn_bayar.setIcon(Icons.LARGE_PAY.get());
        btn_reload.setIcon(Icons.SMALL_RELOAD.get());
        popupMenu = new PopupMenu(txt_voucher_id);
        dataHolderList = new DataSearch();
        rd_voucher.setSelected(true);
        
        resetForm();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rd_voucher = new javax.swing.JRadioButton();
        rd_paketdata = new javax.swing.JRadioButton();
        rd_ewallet = new javax.swing.JRadioButton();
        rd_emoney = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_cek = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_batal = new javax.swing.JButton();
        btn_bayar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_reload = new javax.swing.JButton();
        txt_voucher_id = new javax.swing.JTextField();
        txt_tujuan = new javax.swing.JTextField();
        txt_voucher = new javax.swing.JTextField();
        txt_nominal = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jenis produk", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        buttonGroup1.add(rd_voucher);
        rd_voucher.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rd_voucher.setForeground(new java.awt.Color(255, 255, 255));
        rd_voucher.setText("Voucher");
        rd_voucher.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rd_voucherItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rd_paketdata);
        rd_paketdata.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rd_paketdata.setForeground(new java.awt.Color(255, 255, 255));
        rd_paketdata.setText("Paket Data");
        rd_paketdata.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rd_paketdataItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rd_ewallet);
        rd_ewallet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rd_ewallet.setForeground(new java.awt.Color(255, 255, 255));
        rd_ewallet.setText("E-Wallet");
        rd_ewallet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rd_ewalletItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rd_emoney);
        rd_emoney.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rd_emoney.setForeground(new java.awt.Color(255, 255, 255));
        rd_emoney.setText("E-Money");
        rd_emoney.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rd_emoneyItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rd_voucher)
                .addGap(18, 18, 18)
                .addComponent(rd_paketdata)
                .addGap(18, 18, 18)
                .addComponent(rd_ewallet)
                .addGap(18, 18, 18)
                .addComponent(rd_emoney)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rd_ewallet)
                        .addComponent(rd_paketdata)
                        .addComponent(rd_emoney))
                    .addComponent(rd_voucher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input pembelian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("1. Nomor HP/Kartu");

        btn_cek.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_cek.setText("Cek");
        btn_cek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cekMouseClicked(evt);
            }
        });
        btn_cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cekActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("2. Voucher ID");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("3. Voucher");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("4. Nominal");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("5. Harga");

        btn_batal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_batal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_batal.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_batal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        btn_bayar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_bayar.setText("Bayar");
        btn_bayar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_bayar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_bayar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_bayar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayarActionPerformed(evt);
            }
        });

        btn_reload.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_reload.setText("Reload");
        btn_reload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reloadActionPerformed(evt);
            }
        });

        txt_voucher_id.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_voucher_id.setPreferredSize(new java.awt.Dimension(64, 25));
        txt_voucher_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_voucher_idMouseClicked(evt);
            }
        });
        txt_voucher_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_voucher_idKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_voucher_idKeyReleased(evt);
            }
        });

        txt_tujuan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_tujuan.setPreferredSize(new java.awt.Dimension(64, 25));
        txt_tujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tujuanActionPerformed(evt);
            }
        });

        txt_voucher.setEditable(false);
        txt_voucher.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_voucher.setPreferredSize(new java.awt.Dimension(64, 25));

        txt_nominal.setEditable(false);
        txt_nominal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_nominal.setPreferredSize(new java.awt.Dimension(64, 25));

        txt_harga.setEditable(false);
        txt_harga.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_harga.setPreferredSize(new java.awt.Dimension(64, 25));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_harga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nominal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_voucher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_tujuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_voucher_id, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cek, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_reload, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_tujuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_cek, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_reload, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_voucher_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_voucher, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_nominal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bayar)
                    .addComponent(btn_batal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void txt_voucher_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_voucher_idKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() != KeyEvent.VK_UP
                && evt.getKeyCode() != KeyEvent.VK_DOWN
                && evt.getKeyCode() != KeyEvent.VK_ENTER
                && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            search();
        }
    }//GEN-LAST:event_txt_voucher_idKeyReleased

    private void txt_voucher_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_voucher_idMouseClicked
        // TODO add your handling code here:
        popupMenu.show();
    }//GEN-LAST:event_txt_voucher_idMouseClicked

    private void txt_voucher_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_voucher_idKeyPressed
        // TODO add your handling code here:
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_UP:
                popupMenu.beforeSelection();
                break;
            case KeyEvent.VK_DOWN:
                popupMenu.afterSelection();
                break;
            case KeyEvent.VK_BACK_SPACE:
                search();
                break;
            case KeyEvent.VK_ENTER:
                product = (VoucherModel) popupMenu.setSelectedValue();
                btn_cek.requestFocus();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_txt_voucher_idKeyPressed

    private void btn_cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cekActionPerformed
        // TODO add your handling code here:
        int opt = Common.showConfirmMessage("Cek pembelian voucher ?", this);
        if (opt == 0) {
            if (validateForm()) {
                performInquiry();
            } else {
                Common.showWarningMessage("Mohon pilih produk terlebih dahulu!", this);
            }
        }
    }//GEN-LAST:event_btn_cekActionPerformed

    private void btn_reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reloadActionPerformed

        int opt = Common.showConfirmMessage("Perbarui halaman module voucher ?", this);
        if(opt == 0){
            resetForm();
            loadData();
            Common.showInfoMessage("Reload data berhasil", this);
        }
    }//GEN-LAST:event_btn_reloadActionPerformed

    private void btn_cekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cekMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_cekMouseClicked

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        int opt = Common.showConfirmMessage("Batalkan Transaksi ?", this);
        if(opt == 0){
            resetForm();
        }
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayarActionPerformed
        // TODO add your handling code here:
        if (billerResponse != null) {
            int opt = Common.showConfirmMessage("Anda ingin melakukan pembayaran \n" 
                    + product.getInfo() + " ke "+ txt_tujuan.getText() + " ?", this);
            if (opt == 0) {
                performPayment();
            }
        } else {
            Common.showWarningMessage("Data transaksi belum valid, silahkan ulangi transaksi!", this);
            resetForm();
        }
    }//GEN-LAST:event_btn_bayarActionPerformed

    private void rd_voucherItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rd_voucherItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == 1){
            loadData();
        }
    }//GEN-LAST:event_rd_voucherItemStateChanged

    private void rd_paketdataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rd_paketdataItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == 1){
            loadData();
        }
    }//GEN-LAST:event_rd_paketdataItemStateChanged

    private void rd_ewalletItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rd_ewalletItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == 1){
            loadData();
        }
    }//GEN-LAST:event_rd_ewalletItemStateChanged

    private void rd_emoneyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rd_emoneyItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == 1){
            loadData();
        }
    }//GEN-LAST:event_rd_emoneyItemStateChanged

    private void txt_tujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tujuanActionPerformed
        // TODO add your handling code here:
        txt_voucher_id.requestFocus();
    }//GEN-LAST:event_txt_tujuanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_bayar;
    private javax.swing.JButton btn_cek;
    private javax.swing.JButton btn_reload;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton rd_emoney;
    private javax.swing.JRadioButton rd_ewallet;
    private javax.swing.JRadioButton rd_paketdata;
    private javax.swing.JRadioButton rd_voucher;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_nominal;
    private javax.swing.JTextField txt_tujuan;
    private javax.swing.JTextField txt_voucher;
    private javax.swing.JTextField txt_voucher_id;
    // End of variables declaration//GEN-END:variables

    @Override
    public final void resetForm() {
        Common.clearText(txt_harga, txt_nominal, txt_tujuan, txt_voucher, txt_voucher_id);
        Common.activateComponent(false, btn_bayar, btn_batal);
        Common.activateComponent(true, btn_cek, btn_reload, txt_tujuan, txt_voucher_id);
        product = null; 
        billerResponse = null;
        txt_tujuan.requestFocus();
    }

    @Override
    public final void initListener() {
    }

    @Override
    public void search() {
        product = null;
        if (txt_tujuan.getText().length() < 4) {
            Common.showWarningMessage("Mohon isi nomor tujuan dengan benar!", this);
            txt_tujuan.requestFocus();
        } else {
            if (txt_voucher_id.getText().length() >= 3) {
                getVoucherID();
            } else {
                popupMenu.hide();
            }
        }
    }

    @Override
    public void loadData() {
        try {
            txt_voucher_id.setText("");
            dataHolderList.clear();
            popupMenu.clear();
            String tProductType = "VCR";
            
            if (rd_voucher.isSelected()) {
                tProductType = "VCR";
            }
            
            if (rd_emoney.isSelected()) {
                tProductType = "EMY";
            }
            
            if (rd_ewallet.isSelected()) {
                tProductType = "EWL";
            }
            
            if (rd_paketdata.isSelected()) {
                tProductType = "PDT";
            }
            
            LinkedList<JSONObject> data = transactionController.getVoucherProductList(tProductType);
            if (data != null && data.size() > 0) {
                data.forEach(dataVoucher -> {
                    String tPrefix = dataVoucher.get("prefix").toString();
                    String tVoucher = dataVoucher.get("voucher_id").toString();
                    String tVoucherName = dataVoucher.get("voucher_name").toString();
                    String tProvider = dataVoucher.get("provider_name").toString();
                    BigDecimal tPrice = new BigDecimal(dataVoucher.getDouble("sale_price"));
                    VoucherModel model = new VoucherModel(tVoucher, tVoucherName, tProvider, tPrefix, tPrice);
                    dataHolderList.putData(model);
                });

            }
        } catch (SQLException e) {
            Common.showErrorMessage("Gagal mencari data produk voucher", this);
            Common.errorLog("[SQLException] Error on get voucher product", e);
        }
    }

    private void getVoucherID() {
        String tVoucherID = txt_voucher_id.getText().trim();
        String tPrefix = txt_tujuan.getText().trim().substring(0, 4);
        popupMenu.show(dataHolderList, tPrefix + "#" + tVoucherID);
        
        if(popupMenu.isEmpty()){
            popupMenu.show(dataHolderList, tVoucherID);
        }

    }

    @Override
    public void performInquiry() {
        try {
            VoucherInquiry request = new VoucherInquiry();
            request.setTujuan(txt_tujuan.getText());
            request.setVoucherid(product.getVoucher_id());
            billerResponse = sendRequest(request);

            if (billerResponse != null) {
                saveTransaction();
                JSONObject tPayload = billerResponse.getPayload();
                txt_voucher.setText(product.getVoucher_name());
                txt_nominal.setText(tPayload.get("nominal").toString());
                txt_harga.setText(product.getPrice_sale().toPlainString());
                Common.activateComponent(true, btn_bayar, btn_batal);
                Common.activateComponent(false, btn_cek, btn_reload, txt_tujuan, txt_voucher_id);
            } else {
                txt_voucher_id.requestFocus();
            }
            
        } catch (JSONException | SQLException e) {
            Common.errorLog("[JSONException | SQLException] Failed to execute Perform voucher inquiry", e);
            Common.showErrorMessage(MessageType.SYSTEM_ERROR, this);
        }catch (Exception e) {
            Common.errorLog("[Exception] Failed to execute Perform voucher inquiry", e);
            Common.showErrorMessage(MessageType.FATAL_ERROR, this);
        }
    }

    @Override
    public void performPayment() {
        try {
            prePostPayment("trx_vcr_sales", billerResponse);
            
            VoucherPayment request = new VoucherPayment(billerResponse, product);
            billerResponse = sendRequest(request);

            if (billerResponse != null) {
                if(billerResponse.getResponseCode() == RC.SUCCESS){
                    updateDataTransaction();
                }
            } else {
                transactionController.updateFailedTransaction("trx_vcr_sales", request);
                resetForm();
            }
        } catch (SQLException e) {
            Common.errorLog("[SQLException] Failed to execute Perform voucher payment", e);
            Common.showErrorMessage(MessageType.SYSTEM_ERROR, this);
            resetForm();
        }catch (Exception e) {
            Common.errorLog("[Exception] Failed to execute Perform voucher payment", e);
            Common.showErrorMessage(MessageType.FATAL_ERROR, this);
            resetForm();
        }
    }

    @Override
    public boolean validateForm() {
        if(product == null){
            product = (VoucherModel) popupMenu.getSelectedModel();
        }
        
        return txt_tujuan.getText().length() > 0
                && txt_voucher_id.getText().length() > 0
                && product != null;
    }

    @Override
    public void updateDataTransaction() {
        try {
            JSONObject resp = billerResponse.getPayload();
            transactionController.updateSuccessTransactionVoucher(resp);
            Common.showInfoMessage(resp.getString("rcm"), this);
            previewStruk(resp.getString("trxid"), "trx_vcr_sales");
            resetForm();
        } catch (JSONException | SQLException e) {
            Common.showErrorMessage(MessageType.SYSTEM_ERROR, this);
            Common.errorLog("[SQLException] Error on get voucher product", e);
            resetForm();
        }
    }

    @Override
    public QueryBuilder contructQueryInsertTransaction() {
        JSONObject resp = billerResponse.getPayload();
        
        QueryBuilder builder = new QueryBuilder("trx_vcr_sales", QueryType.INSERT);
        builder.addEntryValue("id", "UUID()", true);
        builder.addEntryValue("transaction_date", "NOW()", true);
        builder.addEntryValue("user_id", App.environment().getDEU());
        builder.addEntryValue("dest_number", resp.getString("tujuan"));
        builder.addEntryValue("voucher_id", resp.getString("voucherid"));
        builder.addEntryValue("nominal", resp.get("nominal").toString());
        builder.addEntryValue("harga", resp.get("harga").toString());
        builder.addEntryValue("harga_jual", product.getPrice_sale().toPlainString());
        builder.addEntryValue("refnumber", resp.get("refnum").toString());
        builder.addEntryValue("transaction_id", resp.get("trxid").toString());
        
        return builder;
    }

    @Override
    public Field[][] createBodyStruk(JSONObject pTranmainData) {
        return createBodyStrukVoucher(pTranmainData);
    }
}
