-- Script generated by Redgate Compare v1.19.7.21820


-- deployment: Dropping trx_voucher_tranmain...
DROP TABLE trx_voucher_tranmain;


-- deployment: Dropping trx_prepaid_tranmain...
DROP TABLE trx_prepaid_tranmain;


-- deployment: Dropping trx_pospaid_tranmain...
DROP TABLE trx_pospaid_tranmain;


-- deployment: Dropping trx_pdam_tranmain...
DROP TABLE trx_pdam_tranmain;


-- deployment: Dropping trx_multipayment_tranmain...
DROP TABLE trx_multipayment_tranmain;


-- deployment: Dropping log_down_message...
DROP TABLE log_down_message;


-- deployment: Dropping log_biller_message...
DROP TABLE log_biller_message;

